const { Pool } = require('pg');
const { PrismaPg } = require('@prisma/adapter-pg');
const { PrismaClient } = require('@prisma/client');

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is not set. Please run the script with --env-file=.env");
  process.exit(1);
}

const pool = new Pool({ 
  connectionString,
  ssl: { rejectUnauthorized: false }
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const condos = [
  // BANGKOK CONDOS
  {
    slug: "ashton-asoke",
    name: "Ashton Asoke",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 783,
    averagePrice: "฿35,000 - ฿85,000 / month",
    transport: "Direct access to MRT Sukhumvit, 230m to BTS Asoke",
    address: "131 Thanon Asok Montri, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Ashton+Asoke",
    website: "https://www.ananda.co.th",
    nearbyAmenities: ["Terminal 21 Shopping Mall", "Exchange Tower", "Interchange 21", "Srinakharinwirot University"],
    article: "<p>Located in the heart of Bangkok's premier transit hub, <strong>Ashton Asoke</strong> offers residents luxury living with unparalleled convenience. Offering a stunning rooftop sky pool, sky lounge, and fitness center, Ashton Asoke is home to executives and expatriates who demand the finest service.</p><p>For residents at Ashton Asoke, managing laundry is effortless. <strong>That Laundry Shop</strong> provides direct pickup and delivery laundry, dry cleaning, and hand-ironing services. Simply drop your garments off at the lobby or coordinate with our team for door-to-door garment care. We treat every fabric with professional expertise.</p>"
  },
  {
    slug: "beatniq-sukhumvit-32",
    name: "Beatniq Sukhumvit 32",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 197,
    averagePrice: "฿55,000 - ฿130,000 / month",
    transport: "250m to BTS Thong Lo",
    address: "124 Sukhumvit Rd, Khwaeng Khlong Tan, Khet Khlong Toei, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Beatniq+Sukhumvit+32",
    website: "https://www.scasset.com",
    nearbyAmenities: ["Rain Hill Complex", "EmQuartier", "Emporium", "Samitivej Sukhumvit Hospital"],
    article: "<p><strong>Beatniq Sukhumvit 32</strong> boasts an iconic mid-century modern design that stands out in the Bangkok skyline. With smart home features, premium hotel-like concierge services, and beautifully curated residential lounges, Beatniq offers a boutique, upscale living experience.</p><p>To maintain your designer suits, luxury shirts, and delicate silk pieces in pristine condition, rely on <strong>That Laundry Shop</strong>. Our premium dry cleaning service ensures your wardrobe gets professional care. We coordinate with the juristic office or lobby concierge for seamless pickup and delivery at Beatniq.</p>"
  },
  {
    slug: "the-monument-thong-lo",
    name: "The Monument Thong Lo",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 85,
    averagePrice: "฿120,000 - ฿350,000 / month",
    transport: "800m to BTS Thong Lo",
    address: "999 Sukhumvit 55, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Monument+Thong+Lo",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["J Avenue", "The Commons", "Donki Mall Thonglor", "Camillian Hospital"],
    article: "<p>Rising high above the prestigious neighborhood of Thong Lo, <strong>The Monument Thong Lo</strong> is a pet-friendly ultra-luxury development. Offering massive, palatial apartments, butler services, and an iconic swimming pool set in a large garden, it is designed for families who want a spacious, exclusive haven.</p><p>Keep your premium wear looking fresh and impeccably pressed with <strong>That Laundry Shop</strong>. We provide white-glove laundry pickup and delivery, taking care of dry cleaning for designer gowns, delicate items, and everyday laundry. Our staff ensures seamless communication and timely delivery back to your Residence.</p>"
  },
  {
    slug: "marque-sukhumvit",
    name: "Marque Sukhumvit",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 148,
    averagePrice: "฿80,000 - ฿250,000 / month",
    transport: "100m to BTS Phrom Phong",
    address: "599 Sukhumvit Rd, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Marque+Sukhumvit",
    website: "https://www.major-development.com",
    nearbyAmenities: ["Emporium Mall", "EmQuartier Shopping Center", "Benchasiri Park", "Villa Market"],
    article: "<p><strong>Marque Sukhumvit</strong> is a super-luxury high-rise condominium located in the prime Phrom Phong area. Known for its diamond-inspired architectural geometry and state-of-the-art facilities (including a golf simulator and squash court), Marque caters to high-net-worth residents.</p><p>Complement your high-end lifestyle with the premium garment care services of <strong>That Laundry Shop</strong>. We specialize in delicate dry cleaning, hotel-standard pressing, and next-day laundry delivery, ensuring your formal wear and daily attire receive the care they deserve.</p>"
  },
  {
    slug: "saladaeng-one",
    name: "Saladaeng One",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 187,
    averagePrice: "฿50,000 - ฿150,000 / month",
    transport: "400m to MRT Lumphini, 600m to BTS Sala Daeng",
    address: "1 Soi Sala Daeng 1, Khwaeng Silom, Khet Bang Rak, Bangkok 10500",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Saladaeng+One",
    website: "https://www.scasset.com",
    nearbyAmenities: ["Lumphini Park", "Silom Complex Mall", "Chulalongkorn Hospital", "Sathorn Financial Center"],
    article: "<p>Overlooking the green expanse of Lumphini Park, <strong>Saladaeng One</strong> is a super-luxury residence in Sathorn-Silom's business hub. Designed with horizontal white marble panels and floor-to-ceiling windows, Saladaeng One provides unmatched park views and modern luxury amenities.</p><p>Get your laundry sorted without hassle. <strong>That Laundry Shop</strong> picks up and delivers directly to the juristic room or concierge office at Saladaeng One. Our professional dry cleaning preserves your shirts, dresses, and high-quality bedsheets to perfection.</p>"
  },
  {
    slug: "98-wireless",
    name: "98 Wireless",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 77,
    averagePrice: "฿180,000 - ฿600,000 / month",
    transport: "350m to BTS Ploenchit",
    address: "98 Wireless Rd, Khwaeng Lumpini, Khet Pathum Wan, Bangkok 10330",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=98+Wireless",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["Central Embassy", "U.S. Embassy", "Lumpini Park", "Park Hyatt Bangkok"],
    article: "<p>Widely considered one of Southeast Asia's most exclusive addresses, <strong>98 Wireless</strong> is a Beaux-Arts inspired masterpiece on the tree-lined Wireless Road. With custom Ralph Lauren furnishings, Bentley limousine service, and an Olympic-size pool, it offers unmatched global prestige.</p><p>For the residents of 98 Wireless, <strong>That Laundry Shop</strong> delivers white-glove laundry and dry cleaning services. We use eco-friendly solvents and hand-ironing techniques to ensure your couture garments are returned in pristine, flawless condition.</p>"
  },
  {
    slug: "the-sukhothai-residences",
    name: "The Sukhothai Residences",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 196,
    averagePrice: "฿90,000 - ฿280,000 / month",
    transport: "700m to MRT Lumphini",
    address: "3 Soi Sathon 3, Khwaeng Thung Maha Mek, Khet Sathon, Bangkok 10120",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Sukhothai+Residences",
    website: "https://www.sukhothairesidences.com",
    nearbyAmenities: ["The Sukhothai Hotel", "Banyan Tree Spa", "Lumphini Park", "MRT Lumphini"],
    article: "<p><strong>The Sukhothai Residences</strong> is an ultra-luxury condominium integrated with the services of the renowned Sukhothai Hotel. It boasts a 100-meter swimming pool, floating cabanas, and world-class gym facilities, setting the benchmark for residential resort living in central Bangkok.</p><p>Experience professional fabric care at home. <strong>That Laundry Shop</strong> provides luxury laundry, dry cleaning, and linen servicing directly to Sukhothai Residences, coordinating pickups through the hotel-style lobby desk for your convenience.</p>"
  },
  {
    slug: "the-ritz-carlton-residences-bangkok",
    name: "The Ritz-Carlton Residences Bangkok",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 209,
    averagePrice: "฿75,000 - ฿300,000 / month",
    transport: "Direct access to BTS Chong Nonsi",
    address: "114 Naradhiwas Rajanagarindra Rd, Khwaeng Silom, Khet Bang Rak, Bangkok 10500",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Ritz-Carlton+Residences+Bangkok",
    website: "https://www.mahanakhon-residences.com",
    nearbyAmenities: ["Mahanakhon SkyWalk", "Silom Plaza", "BTS Chong Nonsi", "Lumpini Park"],
    article: "<p>Situated inside the iconic pixelated Mahanakhon tower, <strong>The Ritz-Carlton Residences</strong> are the epitome of high-rise luxury. Offering full-service Ritz-Carlton hospitality, personal concierges, sky lounges, and private dining, residents enjoy views of the Chao Phraya River.</p><p>We match the impeccable standards of Ritz-Carlton living with our premium dry cleaning and hand-pressing services. <strong>That Laundry Shop</strong> offers direct pickup and next-day return, taking care of delicate fabrics, suits, and everyday laundry for busy professionals.</p>"
  },
  {
    slug: "vittorio-sukhumvit-39",
    name: "Vittorio Sukhumvit 39",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 88,
    averagePrice: "฿95,000 - ฿260,000 / month",
    transport: "150m to BTS Phrom Phong",
    address: "8 Soi Sukhumvit 39, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Vittorio+Sukhumvit+39",
    website: "https://www.apthai.com",
    nearbyAmenities: ["EmQuartier Shopping Complex", "Emporium Mall", "Benchasiri Park", "BTS Phrom Phong"],
    article: "<p><strong>Vittorio Sukhumvit 39</strong> is an exclusive palazzo-themed residence offering extreme privacy with only 88 units. Featuring Italian marble, private lifts, and a stunning sky club, Vittorio provides a quiet sanctuary just steps from the upscale EmDistrict.</p><p>Enjoy spotless clothes and fresh bedding without lifting a finger. <strong>That Laundry Shop</strong> is the trusted laundry and dry cleaning partner for Vittorio residents. We collect and deliver your garments directly through the concierge team.</p>"
  },
  {
    slug: "khun-by-yoo",
    name: "Khun by Yoo",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 148,
    averagePrice: "฿65,000 - ฿180,000 / month",
    transport: "800m to BTS Thong Lo",
    address: "309 Sukhumvit 55, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Khun+by+Yoo",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["The Commons Thonglor", "J Avenue", "Donki Mall", "BTS Thong Lo"],
    article: "<p>Designed by the world-famous designer Philippe Starck and YOO Studio, <strong>Khun by Yoo</strong> is a design-centric luxury condo in the trendy Thong Lo district. Boasting copper-toned facade panels, a heated sky pool, and a private screening room, it is perfect for modern creative minds.</p><p>Keep your trendy designer clothes in top shape. <strong>That Laundry Shop</strong> provides specialized dry cleaning and eco-friendly laundry service with quick pickups from the lobby at Khun by Yoo.</p>"
  },
  {
    slug: "the-bangkok-sathorn",
    name: "The Bangkok Sathorn",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 468,
    averagePrice: "฿45,000 - ฿120,000 / month",
    transport: "Adjacent to BTS Surasak",
    address: "22 South Sathon Rd, Khwaeng Yan Nawa, Khet Sathon, Bangkok 10120",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Bangkok+Sathorn",
    website: "https://www.lh.co.th",
    nearbyAmenities: ["Saint Louis Hospital", "Blue Elephant Cooking School", "BTS Surasak", "King Power Mahanakhon"],
    article: "<p>Featuring private elevator access for every unit and a gorgeous rooftop sky pool, <strong>The Bangkok Sathorn</strong> is a resort-style oasis in Sathorn's financial center. Its lush tropical landscaping and quiet design separate residents from the bustling city outside.</p><p>For hassle-free garment care, trust <strong>That Laundry Shop</strong>. We provide premium wash, fold, dry cleaning, and pressing services directly to residents of The Bangkok Sathorn, ensuring professional results on every order.</p>"
  },
  {
    slug: "estelle-phrom-phong",
    name: "Estelle Phrom Phong",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 146,
    averagePrice: "฿60,000 - ฿220,000 / month",
    transport: "200m to BTS Phrom Phong",
    address: "26 Sukhumvit Rd, Khwaeng Khlong Tan, Khet Khlong Toei, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Estelle+Phrom+Phong",
    website: "https://www.raimonland.com",
    nearbyAmenities: ["Emporium", "EmQuartier", "Benchasiri Park", "Fuji Supermarket"],
    article: "<p><strong>The Estelle Phrom Phong</strong> is an ultra-luxury high-rise condominium designed as an urban oasis. Featuring Japanese-inspired Zen design elements, private onsen, chlorine-free pool, and guest suites, it is a peaceful enclave in the heart of Sukhumvit.</p><p>Ensure your business suits and casual wear get professional treatment. <strong>That Laundry Shop</strong> provides luxury dry cleaning and laundry services with easy drop-offs at Estelle's concierge desk.</p>"
  },
  {
    slug: "hyde-heritage-thonglor",
    name: "Hyde Heritage Thonglor",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 311,
    averagePrice: "฿50,000 - ฿140,000 / month",
    transport: "250m to BTS Thong Lo",
    address: "1199 Sukhumvit Rd, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Hyde+Heritage+Thonglor",
    website: "https://www.hydeheritage.com",
    nearbyAmenities: ["Major Cineplex Ekkamai", "Gateway Ekkamai", "Sukhumvit Hospital", "BTS Thong Lo"],
    article: "<p>Taking inspiration from classic New York luxury architecture, <strong>Hyde Heritage Thonglor</strong> offers over 28 facility zones, including a sky pool, glass house lounge, and theater room. It delivers high-end hospitality services to all its residents.</p><p>We provide prompt laundry, dry cleaning, and garment care services at Hyde Heritage. <strong>That Laundry Shop</strong> coordinates pickups with the front desk so your fresh clothes are ready when you need them.</p>"
  },
  {
    slug: "park-origin-phrom-phong",
    name: "Park Origin Phrom Phong",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 940,
    averagePrice: "฿25,000 - ฿75,000 / month",
    transport: "600m to BTS Phrom Phong",
    address: "128 Soi Sukhumvit 24, Khwaeng Khlong Tan, Khet Khlong Toei, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Park+Origin+Phrom+Phong",
    website: "https://www.origin.co.th",
    nearbyAmenities: ["EmQuartier", "K-Village", "Benchasiri Park", "BTS Phrom Phong"],
    article: "<p>Surrounded by a massive private park, <strong>Park Origin Phrom Phong</strong> (formerly Park 24) is a premium condominium complex in Sukhumvit 24. With dynamic city views, sky pools, and huge fitness spaces, it blends central city convenience with green living.</p><p>Save time on your laundry chores. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of all towers in Park Origin Phrom Phong, keeping your clothes smelling fresh and looking clean.</p>"
  },
  {
    slug: "celes-asoke",
    name: "Celes Asoke",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 217,
    averagePrice: "฿40,000 - ฿100,000 / month",
    transport: "150m to MRT Sukhumvit, 200m to BTS Asoke",
    address: "10 Sukhumvit 21 Rd, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Celes+Asoke",
    website: "https://www.celes-asoke.com",
    nearbyAmenities: ["Terminal 21", "Interchange 21", "Siam Society", "Bumrungrad International Hospital"],
    article: "<p><strong>Celes Asoke</strong> is a luxury high-rise condominium located at the prime intersection of Asoke. Featuring a modern glass design, virtual fitness rooms, sky pool, and alfresco dining terrace, Celes offers a cosmopolitan urban sanctuary.</p><p>For professional dry cleaning and quick laundry services, trust <strong>That Laundry Shop</strong>. We collect your garments directly from Celes Asoke lobby or juristic locker system for a seamless experience.</p>"
  },
  {
    slug: "muniq-sukhumvit-23",
    name: "Muniq Sukhumvit 23",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 201,
    averagePrice: "฿38,000 - ฿90,000 / month",
    transport: "300m to MRT Sukhumvit, 400m to BTS Asoke",
    address: "33 Sukhumvit 23 Rd, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Muniq+Sukhumvit+23",
    website: "https://www.major-development.com",
    nearbyAmenities: ["Srinakharinwirot University", "Terminal 21", "Prasanmit Plaza", "MRT Sukhumvit"],
    article: "<p>Blending modern elegance with classic art deco details, <strong>Muniq Sukhumvit 23</strong> is a luxury high-rise condo. The building offers an automated parking system, high-ceiling lobbies, and a beautiful pool overlooking Asoke.</p><p>Make laundry day a breeze. <strong>That Laundry Shop</strong> offers direct pickup and delivery for dry cleaning, bedsheets, and everyday laundry to the lobby desk at Muniq Sukhumvit 23.</p>"
  },
  {
    slug: "the-esse-asoke",
    name: "The Esse Asoke",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 419,
    averagePrice: "฿32,000 - ฿80,000 / month",
    transport: "500m to MRT Phetchaburi, 600m to BTS Asoke",
    address: "38 Sukhumvit 21 Rd, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Esse+Asoke",
    website: "https://www.singhaestate.co.th",
    nearbyAmenities: ["Srinakharinwirot University", "Midtown Asoke", "Singha Complex", "MRT Phetchaburi"],
    article: "<p>Rising 55 stories above the bustling Asoke district, <strong>The Esse Asoke</strong> is a premium luxury residential tower. Offering a high level of privacy, large sky terraces, golf simulator, sky gym, and an infinity pool, it represents the gold standard of Asoke living.</p><p>Keep your professional attire crisp and immaculate. <strong>That Laundry Shop</strong> provides luxury laundry pickup and dry cleaning services, coordinating with the security and lobby staff at The Esse.</p>"
  },
  {
    slug: "the-reserve-sukhumvit-61",
    name: "The Reserve Sukhumvit 61",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 186,
    averagePrice: "฿45,000 - ฿110,000 / month",
    transport: "900m to BTS Ekkamai",
    address: "59 Soi Sukhumvit 61, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Reserve+Sukhumvit+61",
    website: "https://www.pruksa.com",
    nearbyAmenities: ["Major Ekkamai", "Gateway Ekkamai", "Park Lane Ekkamai", "BTS Ekkamai"],
    article: "<p><strong>The Reserve Sukhumvit 61</strong> is a luxury low-rise condominium built with a hideaway resort concept. Nestled in the quiet residential street of Sukhumvit 61, it features massive private courtyards, high ceilings, and premium European home fittings.</p><p>Protect your high-end fashion items. <strong>That Laundry Shop</strong> provides premium dry cleaning and daily laundry delivery services to residents at The Reserve Sukhumvit 61, offering absolute care for every garment.</p>"
  },
  {
    slug: "kraam-sukhumvit-26",
    name: "Kraam Sukhumvit 26",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 128,
    averagePrice: "฿70,000 - ฿180,000 / month",
    transport: "500m to BTS Phrom Phong",
    address: "26 Soi Sukhumvit 26, Khwaeng Khlong Tan, Khet Khlong Toei, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Kraam+Sukhumvit+26",
    website: "https://www.nyeestate.co.th",
    nearbyAmenities: ["K Village Sukhumvit 26", "Nihonmachi", "Emporium", "BTS Phrom Phong"],
    article: "<p>Crafted as a true home for generations, <strong>Kraam Sukhumvit 26</strong> is a luxury residence designed with green insulation and quiet layouts. Located on the beautiful tree-lined Soi Sukhumvit 26, it offers spacious rooms and family-centric amenities.</p><p>We match the comfort of your home with our bespoke fabric cleaning. <strong>That Laundry Shop</strong> picks up and delivers laundry, dry cleaning, and bed linen services directly to the lobby of Kraam Sukhumvit 26.</p>"
  },
  {
    slug: "circle-sukhumvit-11",
    name: "Circle Sukhumvit 11",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 219,
    averagePrice: "฿28,000 - ฿70,000 / month",
    transport: "700m to BTS Nana",
    address: "33 Soi Sukhumvit 11, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Circle+Sukhumvit+11",
    website: "https://www.circle-sukhumvit-11.com",
    nearbyAmenities: ["Villa Market", "Bumrungrad Hospital", "Nana Plaza", "BTS Nana"],
    article: "<p><strong>Circle Sukhumvit 11</strong> is an eco-friendly modern condominium located in the lively Sukhumvit 11. Boasting movable facade panels, water recycling systems, and a sky pool with underwater music speaker systems, it offers a sustainable urban lifestyle.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services for all apartments in Circle Sukhumvit 11.</p>"
  },
  {
    slug: "wind-sukhumvit-23",
    name: "Wind Sukhumvit 23",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 220,
    averagePrice: "฿26,000 - ฿65,000 / month",
    transport: "400m to MRT Sukhumvit, 500m to BTS Asoke",
    address: "23 Soi Sukhumvit 23, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Wind+Sukhumvit+23",
    website: "https://www.major-development.com",
    nearbyAmenities: ["Terminal 21", "Prasanmit Plaza", "SWU University", "BTS Asoke"],
    article: "<p>With its unique through-ventilation design concept, <strong>Wind Sukhumvit 23</strong> allows fresh air to circulate throughout the building naturally. Nestled in a quiet cul-de-sac of Sukhumvit 23, it provides serenity while keeping you close to Asoke's active lifestyle.</p><p>We provide standard laundry and premium dry cleaning services. <strong>That Laundry Shop</strong> coordinates pickups from Wind Sukhumvit 23 concierge so you can spend your time exploring Bangkok.</p>"
  },
  {
    slug: "royce-private-residences",
    name: "Royce Private Residences",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 162,
    averagePrice: "฿65,000 - ฿180,000 / month",
    transport: "800m to BTS Asoke",
    address: "100 Soi Sukhumvit 31, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Royce+Private+Residences",
    website: "https://www.royceresidences.com",
    nearbyAmenities: ["EmQuartier", "SWU", "Terminal 21", "Samitivej Hospital"],
    article: "<p>Featuring classic British-style gardens, large private spaces, and top-tier facilities (including a private clubhouse, cigar lounge, and expansive pool), <strong>Royce Private Residences</strong> in Sukhumvit 31 is a highly sought-after private compound.</p><p>Complement the elegance of your home with professional garment care. <strong>That Laundry Shop</strong> offers direct pickup and return of dry cleaning and laundry to all residents at Royce.</p>"
  },
  {
    slug: "noble-ploenchit",
    name: "Noble Ploenchit",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 1444,
    averagePrice: "฿40,000 - ฿130,000 / month",
    transport: "Direct skywalk access to BTS Ploenchit",
    address: "1035 Ploenchit Rd, Khwaeng Lumpini, Khet Pathum Wan, Bangkok 10330",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Noble+Ploenchit",
    website: "https://www.nobledevelopment.com",
    nearbyAmenities: ["Central Embassy", "Central Chidlom", "Park Ventures", "BTS Ploenchit"],
    article: "<p><strong>Noble Ploenchit</strong> features a futuristic, minimalist architectural style. With direct skywalk access to Ploenchit BTS, private elevators for most units, and a huge 4-rai garden, it provides premium city living on the high-end Ploenchit Road.</p><p>For the ultimate convenience, order your laundry service with <strong>That Laundry Shop</strong>. We pick up from the Noble Ploenchit lobby towers and return your garments fresh and pressed within 24 hours.</p>"
  },
  {
    slug: "noble-be33-sukhumvit",
    name: "Noble BE33 Sukhumvit",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 277,
    averagePrice: "฿28,000 - ฿70,000 / month",
    transport: "600m to BTS Phrom Phong",
    address: "33 Soi Sukhumvit 33, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Noble+BE33+Sukhumvit",
    website: "https://www.nobledevelopment.com",
    nearbyAmenities: ["Villa Market", "EmQuartier", "Fuji Supermarket", "BTS Phrom Phong"],
    article: "<p>Designed around the concept of 'reflecting your identity', <strong>Noble BE33 Sukhumvit</strong> features high-ceiling units, semi-outdoor sky lounges, and a rooftop sky pool. Located in the lively Sukhumvit 33, it is close to top supermarkets and dining spots.</p><p>Keep your clothes clean and fresh. <strong>That Laundry Shop</strong> provides luxury dry cleaning and wash-fold laundry, picking up directly from Noble BE33 lobby desk.</p>"
  },
  {
    slug: "noble-recole-sukhumvit-19",
    name: "Noble Recole Sukhumvit 19",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 288,
    averagePrice: "฿25,000 - ฿60,000 / month",
    transport: "500m to MRT Sukhumvit, 500m to BTS Asoke",
    address: "24 Soi Sukhumvit 19, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Noble+Recole+Sukhumvit+19",
    website: "https://www.nobledevelopment.com",
    nearbyAmenities: ["Terminal 21 Shopping Mall", "Wattana Wittaya Academy", "BTS Asoke", "Robinson Sukhumvit"],
    article: "<p><strong>Noble Recole</strong> is a modern high-rise condominium tucked in the leafy Soi Sukhumvit 19. Perfect for students and urban professionals, it provides a quiet sanctuary with sky gyms, multi-purpose rooms, and Asoke skyline views.</p><p>We keep your clothes looking like new. <strong>That Laundry Shop</strong> is your professional partner for dry cleaning and laundry pickup at Noble Recole.</p>"
  },
  {
    slug: "noble-state-39",
    name: "Noble State 39",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 352,
    averagePrice: "฿32,000 - ฿85,000 / month",
    transport: "800m to BTS Phrom Phong",
    address: "29 Soi Sukhumvit 39, Khwaeng Khlong Tan Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Noble+State+39",
    website: "https://www.nobledevelopment.com",
    nearbyAmenities: ["EmQuartier", "Samitivej Hospital", "Singha Complex", "BTS Phrom Phong"],
    article: "<p>Inspired by classical design updated for the modern age, <strong>Noble State 39</strong> is a premium high-rise in Sukhumvit 39. Featuring creative lounges, sky gardens, and an indoor sky pool, it is ideal for premium Phrom Phong living.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer convenient, high-quality laundry pickup and dry cleaning, delivered right back to your door at Noble State 39.</p>"
  },
  {
    slug: "noble-around-ari",
    name: "Noble Around Ari",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 611,
    averagePrice: "฿22,000 - ฿55,000 / month",
    transport: "90m to BTS Ari",
    address: "308 Phahonyothin Rd, Khwaeng Samsen Nai, Khet Phaya Thai, Bangkok 10400",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Noble+Around+Ari",
    website: "https://www.nobledevelopment.com",
    nearbyAmenities: ["La Villa Ari", "Aree Garden", "Phayathai 2 Hospital", "BTS Ari"],
    article: "<p><strong>Noble Around Ari</strong> is a modern premium residence located in Bangkok's trendy Ari neighborhood. Offering sky lounges, co-working creative spaces, and a gorgeous rooftop deck, it fits the dynamic lifestyle of young executives.</p><p>Maintain your look with <strong>That Laundry Shop</strong>. We offer laundry pickup and dry cleaning directly from Noble Around Ari, returning your clothes fresh and neatly ironed.</p>"
  },
  {
    slug: "edge-sukhumvit-23",
    name: "Edge Sukhumvit 23",
    city: "Bangkok",
    type: "condo",
    stars: 5,
    totalRooms: 443,
    averagePrice: "฿30,000 - ฿75,000 / month",
    transport: "150m to MRT Sukhumvit, 250m to BTS Asoke",
    address: "23 Sukhumvit Rd, Khwaeng Khlong Toei Nuea, Khet Watthana, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Edge+Sukhumvit+23",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["Terminal 21 Shopping Mall", "Interchange 21", "Soi Cowboy", "Jasmine City"],
    article: "<p>Designed to cater to the energetic lifestyle of Asoke, <strong>Edge Sukhumvit 23</strong> features bold colors and modern amenities. Boasting a beautiful outdoor swimming pool, sky lounges, and close proximity to corporate towers, it is popular with expats.</p><p>We take care of your laundry while you take care of business. <strong>That Laundry Shop</strong> provides luxury wash-fold and dry cleaning services with easy pickup from Edge Sukhumvit 23 lobby.</p>"
  },
  {
    slug: "q-chidlom-phetchaburi",
    name: "Q Chidlom-Phetchaburi",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 352,
    averagePrice: "฿28,000 - ฿65,000 / month",
    transport: "650m to BTS Chidlom",
    address: "1012 Phetchaburi Rd, Khwaeng Makkasan, Khet Ratchathewi, Bangkok 10400",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Q+Chidlom-Phetchaburi",
    website: "https://www.ananda.co.th",
    nearbyAmenities: ["The Palladium World Shopping", "CentralWorld", "Platinum Fashion Mall", "BTS Chidlom"],
    article: "<p><strong>Q Chidlom-Phetchaburi</strong> is a futuristic high-rise featuring a dramatic floating park, rooftop infinity pool, and a high-end social club. Located near the commercial district of Pratunam and Chidlom, it is ideal for metropolitan shoppers.</p><p>Keep your clothes pristine. <strong>That Laundry Shop</strong> provides premium dry cleaning and daily laundry delivery at Q Chidlom, ensuring prompt collection from the lobby.</p>"
  },
  {
    slug: "the-line-sukhumvit-101",
    name: "The Line Sukhumvit 101",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 778,
    averagePrice: "฿18,000 - ฿40,000 / month",
    transport: "250m to BTS Punnawithi",
    address: "3007 Sukhumvit Rd, Khwaeng Bang Chak, Khet Phra Khanong, Bangkok 10260",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Line+Sukhumvit+101",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["True Digital Park", "Anglo Singapore International School", "BTS Punnawithi", "101 Third Place"],
    article: "<p>Designed as a co-living hub, <strong>The Line Sukhumvit 101</strong> features high-ceiling units, creative coworking spaces, and a rooftop sports court. It is a modern luxury hub in Bangkok's eastern business corridor.</p><p>We handle your laundry while you work. <strong>That Laundry Shop</strong> offers direct pickup and delivery for wash, fold, dry cleaning, and ironing for residents at The Line 101.</p>"
  },
  {
    slug: "the-line-asoke-ratchada",
    name: "The Line Asoke-Ratchada",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 473,
    averagePrice: "฿22,000 - ฿50,000 / month",
    transport: "300m to MRT Phra Ram 9",
    address: "88 Din Daeng Rd, Khwaeng Makkasan, Khet Ratchathewi, Bangkok 10400",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Line+Asoke-Ratchada",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["Central Plaza Grand Rama 9", "Fortune Town", "G Tower", "MRT Phra Ram 9"],
    article: "<p><strong>The Line Asoke-Ratchada</strong> is situated in the new central business district of Rama IX. Boasting modern high-rise facilities, dynamic city views, and close access to office hubs, it is an active metropolitan residence.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at The Line.</p>"
  },
  {
    slug: "life-asoke-hype",
    name: "Life Asoke Hype",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 1253,
    averagePrice: "฿19,000 - ฿45,000 / month",
    transport: "300m to MRT Phra Ram 9, 600m to ARL Makkasan",
    address: "25 Thanon Asok-Din Daeng, Khwaeng Makkasan, Khet Ratchathewi, Bangkok 10400",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Life+Asoke+Hype",
    website: "https://www.apthai.com",
    nearbyAmenities: ["Fortune Town", "Central Rama 9", "Show DC Mall", "ARL Makkasan"],
    article: "<p>Featuring a unique eclectic design, <strong>Life Asoke Hype</strong> offers creative co-working spaces, a sky pool, and a rooftop athletic lounge. Its proximity to both MRT and Airport Link makes it ideal for frequent travelers.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer swift wash-fold and dry cleaning services with direct collection from the lobby at Life Asoke Hype.</p>"
  },
  {
    slug: "life-sukhumvit-48",
    name: "Life Sukhumvit 48",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 612,
    averagePrice: "฿16,000 - ฿35,000 / month",
    transport: "600m to BTS Phra Khanong",
    address: "48 Sukhumvit Rd, Khwaeng Phra Khanong, Khet Khlong Toei, Bangkok 10110",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Life+Sukhumvit+48",
    website: "https://www.apthai.com",
    nearbyAmenities: ["W District", "Summer Hill Mall", "Tesco Lotus On Nut", "BTS Phra Khanong"],
    article: "<p><strong>Life Sukhumvit 48</strong> is a premium double-tower condominium located in Phra Khanong. With rooftop swimming pools, large standard gyms, and a cozy co-working space, it provides high-value premium living on Sukhumvit Road.</p><p>Stay fresh with <strong>That Laundry Shop</strong>. We provide professional wash, fold, and dry cleaning services with daily pickups at Life Sukhumvit 48 lobby.</p>"
  },
  {
    slug: "life-one-wireless",
    name: "Life One Wireless",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 1344,
    averagePrice: "฿24,000 - ฿60,000 / month",
    transport: "600m to BTS Ploenchit",
    address: "1 Wireless Rd, Khwaeng Lumpini, Khet Pathum Wan, Bangkok 10330",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Life+One+Wireless",
    website: "https://www.apthai.com",
    nearbyAmenities: ["Central Embassy", "BDMS Wellness Clinic", "CentralWorld", "BTS Ploenchit"],
    article: "<p>Located on the prestigious Wireless Road, <strong>Life One Wireless</strong> features beautiful architecture reflecting classical Thai heritage. Offering a sky-high garden, sky pool, and high-ceiling library, it provides prime city living at a premium standard.</p><p>Enjoy convenient laundry service from <strong>That Laundry Shop</strong>. We collect your bags from the Life One Wireless concierge desk and return everything beautifully pressed.</p>"
  },
  {
    slug: "ideo-q-chula-samyan",
    name: "Ideo Q Chula-Samyan",
    city: "Bangkok",
    type: "condo",
    stars: 4,
    totalRooms: 1598,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "350m to MRT Sam Yan",
    address: "660 Rama IV Rd, Khwaeng Maha Phruttharam, Khet Bang Rak, Bangkok 10500",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Ideo+Q+Chula-Samyan",
    website: "https://www.ananda.co.th",
    nearbyAmenities: ["Samyan Mitrtown", "Chulalongkorn University", "Chamchuri Square", "MRT Sam Yan"],
    article: "<p><strong>Ideo Q Chula-Samyan</strong> is a premium high-rise featuring extensive academic libraries, study zones, sky-high pools, and digital lounges. Highly popular with students and medical professionals, it is a bustling modern hub.</p><p>We take care of your laundry while you study. <strong>That Laundry Shop</strong> provides premium laundry and dry cleaning pickup directly from the Chula-Samyan lobby.</p>"
  },

  // PATTAYA CONDOS
  {
    slug: "riviera-wongamat",
    name: "The Riviera Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 979,
    averagePrice: "฿25,000 - ฿70,000 / month",
    transport: "200m to Wongamat Beach, 10 min to Central Marina",
    address: "Naklua Soi 16, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Riviera+Wongamat",
    website: "https://www.therivieragroup-thailand.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Terminal 21 Pattaya", "Central Marina"],
    article: "<p>Rising above the exclusive Wongamat Beach, <strong>The Riviera Wongamat</strong> is an award-winning luxury residence. Boasting multi-level infinity sky pools, dynamic ocean-view gyms, and lush landscape gardens, it offers a resort life in North Pattaya.</p><p>For residents at Wongamat, laundry is a breeze. <strong>That Laundry Shop</strong> collects dry cleaning, wet laundry, and bed linens directly from the Riviera Wongamat front desk, returning them fresh and spotless.</p>"
  },
  {
    slug: "riviera-jomtien",
    name: "The Riviera Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 1075,
    averagePrice: "฿20,000 - ฿60,000 / month",
    transport: "300m to Jomtien Beach, 15 min to Central Pattaya",
    address: "Jomtien Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Riviera+Jomtien",
    website: "https://www.therivieragroup-thailand.com",
    nearbyAmenities: ["Jomtien Beach", "Jomtien Night Market", "Tiger Park Pattaya", "Underwater World"],
    article: "<p><strong>The Riviera Jomtien</strong> is a luxury high-rise designed to capture the essence of coastal living. Featuring a dramatic sky pool, multiple garden decks, a kids club, and an oceanfront lounge, it is a highly popular vacation residence.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the Jomtien lobby and delivers it back clean and ironed.</p>"
  },
  {
    slug: "riviera-monaco",
    name: "The Riviera Monaco",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 412,
    averagePrice: "฿22,000 - ฿55,000 / month",
    transport: "150m to Na Jomtien Beach",
    address: "Na Jomtien Soi 4, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Riviera+Monaco",
    website: "https://www.therivieragroup-thailand.com",
    nearbyAmenities: ["Na Jomtien Beach", "Ocean Marina Yacht Club", "Mimosa Pattaya", "Cartoon Network Amazone"],
    article: "<p>Featuring a sophisticated Monaco-style luxury design, <strong>The Riviera Monaco</strong> is a boutique residence near Na Jomtien's quiet beach. It offers floating pools, a professional tennis court, sky bar, and luxury suites.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We provide premium wash, fold, dry cleaning, and pressing directly to Riviera Monaco residents with easy pickups.</p>"
  },
  {
    slug: "northpoint-pattaya",
    name: "Northpoint Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 376,
    averagePrice: "฿35,000 - ฿90,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 18, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Northpoint+Pattaya",
    website: "https://www.raimonland.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Windmill Plaza", "Pattaya Beach"],
    article: "<p><strong>Northpoint Pattaya</strong> is a landmark dual-tower luxury beachfront condominium located on Wongamat Beach. With direct private beach access, a sky gym, large pools, and professional management, it caters to exclusive beach lovers.</p><p>Maintain your holiday resort wear. <strong>That Laundry Shop</strong> provides luxury dry cleaning and wash-fold laundry, picking up directly from Northpoint's lobby reception.</p>"
  },
  {
    slug: "reflection-jomtien",
    name: "Reflection Jomtien Beach Oceanfront",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 335,
    averagePrice: "฿30,000 - ฿85,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Na Jomtien Beach Road, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Reflection+Jomtien+Beach",
    website: "https://www.major-development.com",
    nearbyAmenities: ["Jomtien Beach", "Glass House Pattaya", "Banya Cafe", "Ocean Marina"],
    article: "<p>Featuring spectacular floor-to-ceiling sea views from every single unit, <strong>Reflection Jomtien Beach</strong> is an iconic super-luxury high-rise. Its facility deck contains tennis courts, standard pools, and private sky clubs.</p><p>We provide prompt laundry, dry cleaning, and bed linen washing services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at Reflection Jomtien.</p>"
  },
  {
    slug: "cetus-beachfront",
    name: "Cetus Beachfront Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 310,
    averagePrice: "฿22,000 - ฿55,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Cetus+Beachfront+Pattaya",
    website: "http://www.cetuscondo.com",
    nearbyAmenities: ["Jomtien Beach", "Pupen Seafood", "Lung Sawai Restaurant", "Floating Market"],
    article: "<p><strong>Cetus Beachfront</strong> offers a resort-style villa and tower living concept. Known for its warm wood finishes and natural stone architecture, Cetus features infinity-edge sky pools and oceanfront fitness centers.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of Cetus Beachfront Pattaya, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "copacabana-beach-jomtien",
    name: "Copacabana Beach Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 1644,
    averagePrice: "฿25,000 - ฿70,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Copacabana+Beach+Jomtien",
    website: "https://www.copacabanajomtien.com",
    nearbyAmenities: ["Jomtien Beach", "Night Market", "Sports Arena Jomtien", "Colosseum Show"],
    article: "<p><strong>Copacabana Beach Jomtien</strong> is a newly completed luxury skyscraper offering active beach lifestyles. With a rooftop pool on the 59th floor, high-speed elevators, and a private beach club, it is a prime choice for tourists and residents.</p><p>Keep your vacation wardrobe fresh. <strong>That Laundry Shop</strong> provides luxury wash-fold and dry cleaning services with easy pickup from Copacabana lobby.</p>"
  },
  {
    slug: "unixx-south-pattaya",
    name: "Unixx South Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1207,
    averagePrice: "฿12,000 - ฿30,000 / month",
    transport: "5 min to Bali Hai Pier, 10 min to Walking Street",
    address: "Pratumnak Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Unixx+South+Pattaya",
    website: "https://www.unixxpattaya.com",
    nearbyAmenities: ["Pratumnak Hill", "Bali Hai Pier", "Pattaya Viewpoint", "Walking Street"],
    article: "<p>Nestled at the base of Pratumnak Hill, <strong>Unixx South Pattaya</strong> is a resort-style high-rise development. Featuring large family pools, climbing walls, sky gardens, and close proximity to Bali Hai Pier, it offers high-value modern living.</p><p>Enjoy spotless clothes and fresh bedding. <strong>That Laundry Shop</strong> is the trusted laundry and dry cleaning partner for Unixx residents. We collect and deliver your garments directly through the concierge team.</p>"
  },
  {
    slug: "sands-pratumnak",
    name: "Sands Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 286,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "100m to Pratumnak Beach",
    address: "Pratumnak Soi 5, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Sands+Pratumnak",
    website: "http://www.sandspattaya.com",
    nearbyAmenities: ["Pratumnak Beach", "Chocolate Factory Pattaya", "Sky Gallery Restaurant", "Big Buddha Temple"],
    article: "<p><strong>Sands Pratumnak</strong> is a high-end boutique condominium located in the prestigious Pratumnak Hill neighborhood. Boasting modern glass styling, sunset ocean views, and close beach access, it is a quiet beach sanctuary.</p><p>We keep your clothes looking like new. <strong>That Laundry Shop</strong> is your professional partner for dry cleaning and laundry pickup at Sands Pratumnak.</p>"
  },
  {
    slug: "edge-central-pattaya",
    name: "Edge Central Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 603,
    averagePrice: "฿20,000 - ฿55,000 / month",
    transport: "300m to Central Festival Pattaya Beach",
    address: "Pattaya Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Edge+Central+Pattaya",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["Central Festival Pattaya", "Mike Shopping Mall", "Pattaya Beach", "Walking Street"],
    article: "<p>Right in the epicenter of Pattaya's entertainment district, <strong>Edge Central Pattaya</strong> is a luxury skyscraper. Featuring a heated golden sky pool, fitness center, social clubs, and stunning harbor views, it fits active lifestyles.</p><p>Complement your high-end lifestyle with the premium garment care services of <strong>That Laundry Shop</strong>. We specialize in delicate dry cleaning, hotel-standard pressing, and next-day laundry delivery at Edge.</p>"
  },
  {
    slug: "grand-solaire",
    name: "Grand Solaire Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 2326,
    averagePrice: "฿25,000 - ฿80,000 / month",
    transport: "5 min to Bali Hai Pier, 10 min to Jomtien Beach",
    address: "Thappraya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Grand+Solaire+Pattaya",
    website: "https://www.grandsolaire.com",
    nearbyAmenities: ["Thappraya Restaurants", "Bali Hai Pier", "EasyKart Pattaya", "Pratumnak Hill"],
    article: "<p><strong>Grand Solaire</strong> is a newly completed super-project offering iconic hotel-like residences. Rising high above Thappraya Road, it features high-end sporting facilities, wave pools, private sky pools, and absolute luxury management.</p><p>Enjoy convenient laundry service from <strong>That Laundry Shop</strong>. We collect your bags from the Grand Solaire concierge desk and return everything beautifully pressed.</p>"
  },
  {
    slug: "marina-golden-bay",
    name: "Marina Golden Bay",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1800,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "5 min to South Pattaya Road",
    address: "Thepprasit Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Marina+Golden+Bay+Pattaya",
    website: "http://www.marinagoldenbay.com",
    nearbyAmenities: ["Thepprasit Night Market", "Outlet Mall Pattaya", "Big C South Pattaya", "Colosseum Show"],
    article: "<p>Featuring a unique wave design representing sails, <strong>Marina Golden Bay</strong> is a monumental landmark in central Pattaya. Offering sky lounges, shopping centers inside the grounds, and luxury pools, it is a self-contained city.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services for all apartments in Marina Golden Bay.</p>"
  },
  {
    slug: "the-base-central-pattaya",
    name: "The Base Central Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1112,
    averagePrice: "฿14,000 - ฿35,000 / month",
    transport: "300m to Central Festival, 400m to Pattaya Beach",
    address: "Pattaya Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Base+Central+Pattaya",
    website: "https://www.sansiri.com",
    nearbyAmenities: ["Central Festival Pattaya Beach", "The Avenue Pattaya", "Pattaya Beach Road", "Mike Shopping Mall"],
    article: "<p><strong>The Base Central Pattaya</strong> is a highly popular modern high-rise. Its rooftop infinity pool offers one of the best views of Pattaya Bay, making it highly sought-after by holidaymakers and long-term expatriates.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the front desk of The Base and delivers it back clean and ironed.</p>"
  },
  {
    slug: "centric-sea-pattaya",
    name: "Centric Sea Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 999,
    averagePrice: "฿15,000 - ฿40,000 / month",
    transport: "500m to Pattaya Beach, 10 min to Terminal 21",
    address: "Pattaya Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Centric+Sea+Pattaya",
    website: "https://www.scasset.com",
    nearbyAmenities: ["Terminal 21 Pattaya", "Hard Rock Cafe", "Alcazar Cabaret", "Pattaya Beach"],
    article: "<p>Designed with a concept inspired by the sky, sun, and sea, <strong>Centric Sea Pattaya</strong> is a premium triple-building complex. With rooftop pools, sky gyms, and convenient access to both North and Central Pattaya, it offers resort living.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at Centric Sea.</p>"
  },
  {
    slug: "pattaya-posh",
    name: "Pattaya Posh",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 439,
    averagePrice: "฿12,000 - ฿30,000 / month",
    transport: "200m to Pattaya Bus Terminal, 10 min to Terminal 21",
    address: "North Pattaya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Pattaya+Posh",
    website: "https://www.pattayaposh.com",
    nearbyAmenities: ["Pattaya Bus Terminal", "Makro North Pattaya", "Tesco Lotus North Pattaya", "Terminal 21 Pattaya"],
    article: "<p>Located at the gateway of Pattaya on North Pattaya Road, <strong>Pattaya Posh</strong> offers easy access to Bangkok routes and Pattaya Central. Featuring a rooftop infinity pool and standard gym, it is perfect for business commuters.</p><p>For professional dry cleaning and quick laundry services, trust <strong>That Laundry Shop</strong>. We collect your garments directly from Pattaya Posh lobby desk for a seamless experience.</p>"
  }
];

async function seed() {
  console.log(`Seeding started. Total condos to seed: ${condos.length}`);
  
  let successCount = 0;
  let failCount = 0;
  
  for (const condo of condos) {
    try {
      await prisma.location.upsert({
        where: { slug: condo.slug },
        update: {
          name: condo.name,
          city: condo.city,
          type: condo.type,
          stars: condo.stars,
          totalRooms: condo.totalRooms,
          averagePrice: condo.averagePrice,
          transport: condo.transport,
          address: condo.address,
          image: condo.image,
          mapLink: condo.mapLink,
          website: condo.website,
          nearbyAmenities: condo.nearbyAmenities,
          article: condo.article
        },
        create: condo
      });
      console.log(`Successfully seeded/updated: ${condo.name}`);
      successCount++;
    } catch (err) {
      console.error(`Failed to seed: ${condo.name}`, err);
      failCount++;
    }
  }
  
  console.log(`Seeding completed. Success: ${successCount}, Failed: ${failCount}`);
  
  // Clean up and revalidate public routes
  try {
    const { revalidatePath } = require('next/cache');
    revalidatePath("/[locale]/hotels", "page");
    revalidatePath("/[locale]/condominiums", "page");
    revalidatePath("/[locale]/hotels/[slug]", "page");
    revalidatePath("/[locale]/condominiums/[slug]", "page");
    console.log("Revalidated frontend cache paths successfully.");
  } catch (revalErr) {
    // next/cache can only be imported in Next.js runtime. 
    // If we run this script directly via Node command line, next/cache will fail to import.
    // That is perfectly fine since the Next.js dev server will rebuild/compile on access anyway,
    // or when the user loads the dashboard and updates an item.
    console.log("Note: Skipped runtime Next.js cache revalidation (normal when seeding outside Next.js process).");
  }
}

seed()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
    pool.end();
  });
