const { Pool } = require('pg');
const { PrismaPg } = require('@prisma/adapter-pg');
const { PrismaClient } = require('@prisma/client');

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is not set. Please run the script with --env-file=.env");
  process.exit(1);
}

const pool = new Pool({ 
  connectionString,
  ssl: { rejectUnauthorized: false }
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const pattayaCondos = [
  {
    slug: "riviera-ocean-drive",
    name: "The Riviera Ocean Drive",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 513,
    averagePrice: "฿22,000 - ฿50,000 / month",
    transport: "On Jomtien Second Road, 400m to Jomtien Beach",
    address: "Jomtien Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Riviera+Ocean+Drive",
    website: "https://therivieragroup-thailand.com",
    nearbyAmenities: ["Jomtien Beach", "Jomtien Night Market", "Rompho Market", "Pan Pan Restaurant"],
    article: "<p><strong>The Riviera Ocean Drive</strong> is a luxury high-rise condominium in Jomtien. Featuring award-winning architecture and design, it offers a stunning rooftop infinity pool, card room, fitness club, and panoramic sea views.</p><p>For hassle-free garment care, trust <strong>That Laundry Shop</strong>. We provide premium laundry, dry cleaning, and ironing services with direct pickup and delivery for residents at The Riviera Ocean Drive.</p>"
  },
  {
    slug: "once-pattaya",
    name: "Once Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 327,
    averagePrice: "฿24,000 - ฿60,000 / month",
    transport: "On Chalermprakiat Road, 5 min to Terminal 21 Pattaya",
    address: "Chalermprakiat Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Once+Pattaya",
    website: "https://www.honour-thailand.com",
    nearbyAmenities: ["Terminal 21 Pattaya", "Tesco Lotus North Pattaya", "Pattaya Bus Terminal", "Hard Rock Cafe"],
    article: "<p>Located in the commercial heart of North Pattaya, <strong>Once Pattaya</strong> offers luxury living with dynamic urban facilities, including a rooftop cloud pool, sky lounge, and private co-working spaces.</p><p>Keep your clothes looking brand new. <strong>That Laundry Shop</strong> is your professional partner for dry cleaning and laundry pickup at Once Pattaya.</p>"
  },
  {
    slug: "arcadia-beach-resort",
    name: "Arcadia Beach Resort",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1118,
    averagePrice: "฿10,000 - ฿25,000 / month",
    transport: "Located in South Pattaya, 10 min to Walking Street",
    address: "Thappraya Soi 9, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Arcadia+Beach+Resort",
    website: "https://www.arcadiapattaya.com",
    nearbyAmenities: ["Bali Hai Pier", "Pattaya Viewpoint", "Thappraya Restaurants", "Walking Street"],
    article: "<p>Offering a massive lagoon-style swimming pool and resort-style living, <strong>Arcadia Beach Resort</strong> in South Pattaya is popular with long-term expats and travelers seeking high-value premium living.</p><p>We provide convenient wash, fold, and dry cleaning services. <strong>That Laundry Shop</strong> coordinates pickups from Arcadia Beach Resort reception so you can enjoy your resort lifestyle.</p>"
  },
  {
    slug: "arcadia-beach-continental",
    name: "Arcadia Beach Continental",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1350,
    averagePrice: "฿12,000 - ฿28,000 / month",
    transport: "Located in South Pattaya, off Thappraya Road",
    address: "Thappraya Soi 5, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Arcadia+Beach+Continental",
    website: "https://www.arcadiapattaya.com",
    nearbyAmenities: ["Pratumnak Hill", "Food Mart Supermarket", "Colosseum Show", "Bali Hai Pier"],
    article: "<p>Featuring European-style theme blocks and a large central beach pool, <strong>Arcadia Beach Continental</strong> brings a continental lifestyle to South Pattaya with modern facilities and cozy apartments.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer swift wash-fold and dry cleaning services with direct collection from the lobby at Arcadia Beach Continental.</p>"
  },
  {
    slug: "arcadia-millennium-tower",
    name: "Arcadia Millennium Tower",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 803,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "On Third Road, 10 min to Walking Street",
    address: "Pattaya Third Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Arcadia+Millennium+Tower",
    website: "https://www.arcadiapattaya.com",
    nearbyAmenities: ["Pattaya Memorial Hospital", "The Avenue Pattaya", "Tukcom IT Mall", "Walking Street"],
    article: "<p><strong>Arcadia Millennium Tower</strong> is a premium high-rise in central Pattaya. Boasting a rooftop swimming pool on the 45th floor, sky gym, game rooms, and easy access to both Central and South Pattaya.</p><p>Complement your high-end lifestyle with the premium garment care of <strong>That Laundry Shop</strong>. We specialize in delicate dry cleaning and next-day laundry delivery at Arcadia Millennium.</p>"
  },
  {
    slug: "olympus-city-garden",
    name: "Olympus City Garden",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1060,
    averagePrice: "฿11,000 - ฿28,000 / month",
    transport: "Located in Central Pattaya, off Soi Khopai",
    address: "Soi Khopai 4, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Olympus+City+Garden",
    website: "https://www.globaltopgroup.com",
    nearbyAmenities: ["Tukcom IT Mall", "Friendship Supermarket", "Pattaya Third Road", "Central Festival"],
    article: "<p>Inspired by classical Mediterranean design, <strong>Olympus City Garden</strong> features a series of low-rise blocks surrounded by swimming pools and jogging tracks, offering a quiet enclave in central Pattaya.</p><p>We collect and deliver your laundry directly through the concierge team at Olympus City Garden. <strong>That Laundry Shop</strong> provides luxury wash, fold, and dry cleaning.</p>"
  },
  {
    slug: "city-garden-pratumnak",
    name: "City Garden Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 157,
    averagePrice: "฿14,000 - ฿35,000 / month",
    transport: "250m to Cozy Beach Pratumnak",
    address: "Kasetsin Soi 1, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=City+Garden+Pratumnak",
    website: "https://www.globaltopgroup.com",
    nearbyAmenities: ["Cozy Beach", "Chocolate Factory", "Sky Gallery Restaurant", "Bali Hai Pier"],
    article: "<p><strong>City Garden Pratumnak</strong> is a boutique low-rise condominium located on Cozy Beach Pratumnak. It features modern architecture, sunset views, high-quality gyms, and close beach access.</p><p>Ensure your beach resort wear gets professional treatment. <strong>That Laundry Shop</strong> provides premium dry cleaning and laundry services with easy drop-offs at the front desk.</p>"
  },
  {
    slug: "city-garden-tropicana",
    name: "City Garden Tropicana",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 188,
    averagePrice: "฿12,000 - ฿32,000 / month",
    transport: "Located in Naklua, 600m to Wongamat Beach",
    address: "Naklua Soi 16/1, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=City+Garden+Tropicana",
    website: "https://www.globaltopgroup.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Windmill Plaza", "Naklua Fish Market"],
    article: "<p>Embodying tropical style and natural serenity, <strong>City Garden Tropicana</strong> in Naklua features lush garden facilities, swimming pools, and rooftop sky decks overlooking Wongamat.</p><p>Stay fresh with <strong>That Laundry Shop</strong>. We provide professional wash, fold, and dry cleaning services with daily pickups at City Garden Tropicana.</p>"
  },
  {
    slug: "city-garden-tower",
    name: "City Garden Tower",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 262,
    averagePrice: "฿15,000 - ฿38,000 / month",
    transport: "Located at the intersection of Third Road and South Pattaya Road",
    address: "South Pattaya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=City+Garden+Tower",
    website: "https://www.globaltopgroup.com",
    nearbyAmenities: ["Tukcom IT Mall", "Friendship Supermarket", "Walking Street", "Pattaya Memorial Hospital"],
    article: "<p><strong>City Garden Tower</strong> is a premium high-rise in South-Central Pattaya. Offering dynamic city and harbor views, a large swimming pool, and high-end fitness clubs, it is popular with business professionals.</p><p>We handle your laundry while you explore. <strong>That Laundry Shop</strong> offers direct pickup and delivery for wash, fold, and dry cleaning at City Garden Tower.</p>"
  },
  {
    slug: "the-peak-towers",
    name: "The Peak Towers Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 474,
    averagePrice: "฿16,000 - ฿42,000 / month",
    transport: "400m to Cozy Beach Pratumnak",
    address: "Kasetsin Soi 9, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Peak+Towers+Pratumnak",
    website: "https://www.thepeaktowers.com",
    nearbyAmenities: ["Cozy Beach", "Royal Varuna Yacht Club", "Chocolate Factory", "Big Buddha Temple"],
    article: "<p><strong>The Peak Towers Pratumnak</strong> is a luxury high-rise offering spectacular ocean views of Jomtien Bay. With high-rise pools, sky gyms, and landscaped play areas, it is a prime choice for families.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer convenient, high-quality laundry pickup and dry cleaning delivered right back to your door at The Peak Towers.</p>"
  },
  {
    slug: "water-park-condo",
    name: "Water Park Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 210,
    averagePrice: "฿10,000 - ฿24,000 / month",
    transport: "On Pratumnak Soi 6, 300m to Pratumnak Beach",
    address: "Pratumnak Soi 6, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Water+Park+Condominium",
    website: "http://www.heightspattaya.com",
    nearbyAmenities: ["Pratumnak Beach", "Patisse Cafe", "Big Buddha", "Pattaya Park Tower"],
    article: "<p><strong>Water Park Condominium</strong> features a rooftop pool and rooftop fitness center overlooking the gulf. Located on Pratumnak Soi 6, it is popular with holidaymakers seeking beach proximity.</p><p>We provide professional dry cleaning and quick laundry services. <strong>That Laundry Shop</strong> collects your garments directly from Water Park lobby desk.</p>"
  },
  {
    slug: "park-royal-3",
    name: "Park Royal 3 Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 140,
    averagePrice: "฿11,000 - ฿26,000 / month",
    transport: "On Pratumnak Soi 5, 400m to Pratumnak Beach",
    address: "Pratumnak Soi 5, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Park+Royal+3+Pratumnak",
    website: "http://www.heightspattaya.com",
    nearbyAmenities: ["Pratumnak Beach", "Chocolate Factory", "Sky Gallery", "Cabbages and Condoms"],
    article: "<p><strong>Park Royal 3 Pratumnak</strong> is a boutique low-rise condominium offering a quiet lifestyle on Pratumnak Hill. With modern amenities, cozy lounges, and tropical landscaping, it is a serene holiday hub.</p><p>Make laundry day a breeze. <strong>That Laundry Shop</strong> offers direct pickup and delivery for dry cleaning and everyday laundry at Park Royal 3.</p>"
  },
  {
    slug: "jewel-pratumnak",
    name: "The Jewel Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 121,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "On Pratumnak Kasetsin Road",
    address: "Kasetsin Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Jewel+Pratumnak",
    website: "https://www.jewelpattaya.com",
    nearbyAmenities: ["Cozy Beach", "Chocolate Factory", "Pattaya Viewpoint", "Bali Hai Pier"],
    article: "<p>Rising elegantly above Cozy Beach, <strong>The Jewel Pratumnak</strong> is a high-end luxury boutique residence. Featuring a rooftop sky pool, modern gymnasium, and designer interior styling, it is a modern coastal gem.</p><p>We provide premium dry cleaning and daily laundry delivery at The Jewel, coordinating pickups from the front reception desk.</p>"
  },
  {
    slug: "vision-pratumnak",
    name: "The Vision Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 220,
    averagePrice: "฿13,000 - ฿32,000 / month",
    transport: "On Pratumnak Soi 2, 5 min to Pattaya South",
    address: "Pratumnak Soi 2, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Vision+Pratumnak",
    website: "https://www.visionpattaya.com",
    nearbyAmenities: ["Big Buddha Temple", "Pattaya Viewpoint", "Bali Hai Pier", "Walking Street"],
    article: "<p>Perched high on the peak of Pratumnak Hill, <strong>The Vision Pratumnak</strong> offers spectacular 360-degree ocean and city views. With a sky pool, sauna, and modern gym, it is popular with expats seeking panoramic vistas.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services for all units at The Vision.</p>"
  },
  {
    slug: "amari-residences-pattaya",
    name: "Amari Residences Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 279,
    averagePrice: "฿25,000 - ฿65,000 / month",
    transport: "Located on Pratumnak Hill, 5 min to Bali Hai Pier",
    address: "Pratumnak Hill, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Amari+Residences+Pattaya",
    website: "https://www.amariresidences.com",
    nearbyAmenities: ["Bali Hai Pier", "Walking Street", "Royal Varuna Yacht Club", "Cozy Beach"],
    article: "<p><strong>Amari Residences Pattaya</strong> shares the premium services of the Amari hospitality group. Offering luxury high-rise apartments, a sky-high pool, 5-star concierge, and room service, it is the peak of hotel-condo living.</p><p>Enjoy hotel-standard dry cleaning and pressing services at your home. <strong>That Laundry Shop</strong> coordinates pickups from the front desk of Amari Residences.</p>"
  },
  {
    slug: "sands-condo-jomtien",
    name: "Sands Condominium Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 286,
    averagePrice: "฿15,000 - ฿38,000 / month",
    transport: "Fronting Jomtien Second Road",
    address: "Jomtien Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Sands+Condominium+Jomtien",
    website: "http://www.sandspattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Rompho Market", "Sports Arena Jomtien", "Jomtien Night Market"],
    article: "<p>Located on the bustling Jomtien Second Road, <strong>Sands Jomtien</strong> is a modern premium tower. Boasting sunset sea views, sky gardens, and convenient transport links to Central Pattaya, it fits active coastal lifestyles.</p><p>Keep your clothes pristine. <strong>That Laundry Shop</strong> provides premium dry cleaning and daily laundry delivery at Sands Jomtien.</p>"
  },
  {
    slug: "jomtien-plaza-condotel",
    name: "Jomtien Plaza Condotel",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 540,
    averagePrice: "฿16,000 - ฿40,000 / month",
    transport: "At the start of Jomtien Beach Road, 50m to beach",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Jomtien+Plaza+Condotel",
    website: "https://www.jomtienplaza.com",
    nearbyAmenities: ["Jomtien Beach", "Dongtan Beach", "Pan Pan Restaurant", "Food Mart"],
    article: "<p><strong>Jomtien Plaza Condotel</strong> is a classic double-tower condominium situated right at the junction of Jomtien Beach Road. Known for its massive balcony layouts and sunset beach views, it is highly popular with expats.</p><p>We provide prompt laundry, dry cleaning, and bed linen washing services. <strong>That Laundry Shop</strong> coordinates pickups from the reception at Jomtien Plaza.</p>"
  },
  {
    slug: "paradise-park-jomtien",
    name: "Paradise Park Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 507,
    averagePrice: "฿9,000 - ฿22,000 / month",
    transport: "Located in Jomtien, Soi Wat Boon",
    address: "Soi Wat Boon, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Paradise+Park+Jomtien",
    website: "https://www.paradiseparkpattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Wat Boon Temple", "Tesco Lotus Express", "Night Market"],
    article: "<p>Featuring a huge resort-style swimming pool, sandy beaches inside the grounds, and tropical gardens, <strong>Paradise Park Jomtien</strong> offers family holiday apartments in a resort enclave.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of Paradise Park Jomtien, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "amazon-residence-jomtien",
    name: "Amazon Residence Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 795,
    averagePrice: "฿9,000 - ฿24,000 / month",
    transport: "Located in Jomtien, off Wat Boon Road",
    address: "Soi Wat Boon, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Amazon+Residence+Jomtien",
    website: "https://www.amazonresidencepattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Jomtien Night Market", "Tiger Park", "Pattaya Floating Market"],
    article: "<p><strong>Amazon Residence Jomtien</strong> is a jungle-themed resort condominium. Boasting an expansive lagoon pool winding through tropical foliage, floating lounges, and gym facilities, it is a fun vacation destination.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the front desk of Amazon Residence.</p>"
  },
  {
    slug: "seven-seas-resort",
    name: "Seven Seas Resort Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1450,
    averagePrice: "฿10,000 - ฿26,000 / month",
    transport: "Located on Chaiyapruek Road Jomtien",
    address: "Chaiyapruek Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Seven+Seas+Resort+Jomtien",
    website: "https://www.sevenseasresortpattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Chaiyapruek Market", "Macro South Pattaya", "Underwater World"],
    article: "<p>Featuring themed islands (like Madagascar, Bahamas, Bora Bora, and Easter Island) connected by massive swimming pool networks, <strong>Seven Seas Resort</strong> is a family paradise in Jomtien.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at Seven Seas.</p>"
  },
  {
    slug: "seven-seas-cote-d-azur",
    name: "Seven Seas Cote d'Azur",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1308,
    averagePrice: "฿12,000 - ฿30,000 / month",
    transport: "Located in Na Jomtien, 300m to beach",
    address: "Na Jomtien Soi 4, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Seven+Seas+Cote+d'Azur",
    website: "https://www.sevenseasresortpattaya.com",
    nearbyAmenities: ["Na Jomtien Beach", "Mimosa Pattaya", "Ocean Marina Yacht Club", "Cartoon Network"],
    article: "<p><strong>Seven Seas Cote d'Azur</strong> brings the French Riviera to Pattaya. With replica yacht clubs, sandy beaches, cafe terraces, and Cannes-style architecture, it is a premium lifestyle residential project.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services for all apartments in Cote d'Azur.</p>"
  },
  {
    slug: "seven-seas-le-carnival",
    name: "Seven Seas Le Carnival",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1100,
    averagePrice: "฿11,000 - ฿28,000 / month",
    transport: "Located on Thepprasit Soi 9 Jomtien",
    address: "Thepprasit Soi 9, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Seven+Seas+Le+Carnival",
    website: "https://www.sevenseasresortpattaya.com",
    nearbyAmenities: ["Thepprasit Market", "Outlet Mall", "Colosseum Show", "Jomtien Beach"],
    article: "<p>Designed with a festive Rio Carnival theme, <strong>Seven Seas Le Carnival</strong> features dual sky pools, private theaters, indoor gardens, and close proximity to Jomtien beach and shopping outlets.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at Le Carnival.</p>"
  },
  {
    slug: "espana-condo-resort",
    name: "Espana Condo Resort Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1082,
    averagePrice: "฿12,000 - ฿32,000 / month",
    transport: "On Jomtien Second Road",
    address: "Jomtien Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Espana+Condo+Resort+Pattaya",
    website: "https://www.espanapattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Tiger Park", "Floating Market", "Pupen Seafood"],
    article: "<p><strong>Espana Condo Resort</strong> features a Spanish architectural theme, replica windmills, castles, and a large central swimming pool network. It is a family resort condominium in Jomtien.</p><p>Keep your clothes clean and fresh. <strong>That Laundry Shop</strong> provides luxury dry cleaning and wash-fold laundry, picking up directly from Espana lobby desk.</p>"
  },
  {
    slug: "venetian-signature",
    name: "Venetian Signature Condo Resort",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 990,
    averagePrice: "฿11,000 - ฿28,000 / month",
    transport: "Located in Na Jomtien, near Sukhumvit Road",
    address: "Na Jomtien, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Venetian+Signature+Condo+Resort",
    website: "https://www.venetianpattaya.com",
    nearbyAmenities: ["Mimosa Pattaya", "Na Jomtien Beach", "Glass House Pattaya", "Sukhumvit Road"],
    article: "<p>Recreating the canals of Venice, <strong>Venetian Signature</strong> features replica gondolas, Rialto bridges, and a clock tower set around a large swimming pool. It offers a unique residential experience.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at Venetian.</p>"
  },
  {
    slug: "empire-tower",
    name: "Empire Tower Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 440,
    averagePrice: "฿20,000 - ฿50,000 / month",
    transport: "Fronting Jomtien Second Road",
    address: "Jomtien Second Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Empire+Tower+Pattaya",
    website: "https://www.empiretowerpattaya.com",
    nearbyAmenities: ["Jomtien Beach", "Jomtien Night Market", "Rompho Complex", "Tesco Lotus Express"],
    article: "<p><strong>Empire Tower Pattaya</strong> is a luxury hotel-style high-rise. Offering classic skyscraper design, a rooftop sky pool, sunset lounges, and premium concierge services, it fits luxury beach lifestyles.</p><p>We match the impeccable standards of luxury living with our premium dry cleaning and hand-pressing. <strong>That Laundry Shop</strong> offers direct pickup and next-day return at Empire Tower.</p>"
  },
  {
    slug: "wyndham-grand-najomtien",
    name: "Wyndham Grand Na Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 350,
    averagePrice: "฿26,000 - ฿65,000 / month",
    transport: "Direct beach access to Na Jomtien Beach",
    address: "Na Jomtien Beach Road, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Wyndham+Grand+Na+Jomtien",
    website: "https://www.wyndhamgrandnajomtien.com",
    nearbyAmenities: ["Na Jomtien Beach", "Glass House", "Banya Cafe", "Ocean Marina Yacht Club"],
    article: "<p>Featuring full 5-star hotel management by the Wyndham Group, <strong>Wyndham Grand Na Jomtien</strong> offers premium beach residences, private beachfront pools, sunset bars, and spa centers.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at Wyndham Grand.</p>"
  },
  {
    slug: "pure-najomtien",
    name: "Pure Na Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 128,
    averagePrice: "฿35,000 - ฿90,000 / month",
    transport: "Beachfront Na Jomtien Beach",
    address: "Na Jomtien Soi 22, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Pure+Na+Jomtien",
    website: "https://www.purenajomtien.com",
    nearbyAmenities: ["Na Jomtien Beach", "Sea Sand Sun Resort", "Glass House", "Nong Nooch Garden"],
    article: "<p><strong>Pure Na Jomtien</strong> is an award-winning eco-friendly luxury low-rise beachfront residence. Offering absolute private beach access, custom designer gardens, and a peaceful sanctuary, it is home to wealthy executives.</p><p>For the residents of Pure Na Jomtien, <strong>That Laundry Shop</strong> delivers white-glove laundry and dry cleaning services. We pick up from the lobby reception.</p>"
  },
  {
    slug: "veranda-residence",
    name: "Veranda Residence Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 360,
    averagePrice: "฿28,000 - ฿75,000 / month",
    transport: "Direct beach access to Na Jomtien Beach",
    address: "Na Jomtien Beach Road, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Veranda+Residence+Pattaya",
    website: "https://www.verandaresidence.com",
    nearbyAmenities: ["Veranda Resort Pattaya", "Skoop Beach Cafe", "Na Jomtien Beach", "Glass House"],
    article: "<p><strong>Veranda Residence Pattaya</strong> offers upscale beach living with full access to Veranda Resort facilities, including beach clubs, spa centers, standard pools, and fine dining.</p><p>Complement your high-end lifestyle with the premium garment care of <strong>That Laundry Shop</strong>. We specialize in delicate dry cleaning, hotel-standard pressing, and next-day laundry delivery.</p>"
  },
  {
    slug: "aeras-condo",
    name: "Aeras Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 309,
    averagePrice: "฿22,000 - ฿60,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Aeras+Condominium",
    website: "https://www.aerascondo.com",
    nearbyAmenities: ["Jomtien Beach", "Pupen Seafood", "Lung Sawai Seafood", "Sports Arena Jomtien"],
    article: "<p>Offering sea views from every unit and high-rise design, <strong>Aeras Condominium</strong> is situated on Jomtien Beach Road. It features sky gyms, library lounges, pool rooms, and sunset decks.</p><p>Enjoy convenient laundry service from <strong>That Laundry Shop</strong>. We collect your bags from the Aeras lobby desk and return everything beautifully pressed.</p>"
  },
  {
    slug: "zire-wongamat",
    name: "Zire Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 480,
    averagePrice: "฿32,000 - ฿80,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 18, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Zire+Wongamat",
    website: "https://www.raimonland.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Pullman Hotel G", "Terminal 21 Pattaya"],
    article: "<p><strong>Zire Wongamat</strong> is a premier luxury beachfront double-tower condominium on Wongamat Beach. With beachfront pools, tennis courts, and high-quality security, it is a top expat choice in Naklua.</p><p>We keep your clothes looking like new. <strong>That Laundry Shop</strong> is your professional partner for dry cleaning and laundry pickup at Zire Wongamat.</p>"
  },
  {
    slug: "ananya-wongamat",
    name: "Ananya Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 120,
    averagePrice: "฿40,000 - ฿100,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 16, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Ananya+Wongamat",
    website: "https://www.ananyawongamat.com",
    nearbyAmenities: ["Wongamat Beach", "Rim Talay Restaurant", "Sanctuary of Truth", "Windmill Plaza"],
    article: "<p><strong>Ananya Wongamat</strong> is a boutique low-rise beachfront development. Offering massive terraces, private beach gardens, and direct sea access, it is a highly private retreat for wealthy families.</p><p>Complement the elegance of your home with professional garment care. <strong>That Laundry Shop</strong> offers direct pickup and return of dry cleaning and laundry to all residents at Ananya.</p>"
  },
  {
    slug: "wongamat-tower",
    name: "Wongamat Tower",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 361,
    averagePrice: "฿20,000 - ฿55,000 / month",
    transport: "50m to Wongamat Beach",
    address: "Naklua Soi 12, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Wongamat+Tower",
    website: "https://www.wongamattower.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Pullman G", "Central Marina"],
    article: "<p>Rising above Wongamat, <strong>Wongamat Tower</strong> is a modern high-rise designed with floor-to-ceiling glass panel windows. Featuring a sky pool, co-working lounges, and modern fitness facilities, it offers active coastal lifestyles.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the front desk of Wongamat Tower.</p>"
  },
  {
    slug: "wongamat-privacy",
    name: "Wongamat Privacy Residence",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 440,
    averagePrice: "฿12,000 - ฿28,000 / month",
    transport: "Located in Naklua, Soi 16/2",
    address: "Naklua Soi 16/2, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Wongamat+Privacy+Residence",
    website: "https://www.wongamatprivacy.com",
    nearbyAmenities: ["Wongamat Beach", "Windmill Plaza", "Tesco Express Naklua", "Sanctuary of Truth"],
    article: "<p><strong>Wongamat Privacy Residence</strong> offers a quiet residential lifestyle in Naklua. With lush gardens, swimming pools, and tennis courts, it is a serene haven close to Wongamat beach.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of Wongamat Privacy, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "sky-beach-condo",
    name: "Sky Beach Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 420,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 18, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Sky+Beach+Condominium",
    website: "https://www.skybeachpattaya.com",
    nearbyAmenities: ["Wongamat Beach", "Pullman G Hotel", "Surf and Turf Cafe", "Windmill Plaza"],
    article: "<p><strong>Sky Beach Condominium</strong> is a famous high-rise situated right on Wongamat Beach. Boasting beachfront pools, tennis courts, and massive balconies, it has been a favorite for expats for years.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at Sky Beach.</p>"
  },
  {
    slug: "palm-wongamat",
    name: "The Palm Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 544,
    averagePrice: "฿30,000 - ฿85,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 16, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Palm+Wongamat",
    website: "http://www.thepalmpattaya.com",
    nearbyAmenities: ["Wongamat Beach", "Rim Talay Seafood", "Sanctuary of Truth", "Banya Cafe"],
    article: "<p>Featuring a multi-level beachfront pool, private cabanas, and panoramic ocean vistas, <strong>The Palm Wongamat</strong> is an award-winning luxury beachfront condominium in North Pattaya.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at The Palm Wongamat.</p>"
  },
  {
    slug: "sanctuary-wongamat",
    name: "The Sanctuary Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 200,
    averagePrice: "฿32,000 - ฿90,000 / month",
    transport: "Direct beach access to Wongamat Beach",
    address: "Naklua Soi 12, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=The+Sanctuary+Wongamat",
    website: "https://www.sanctuarywongamat.com",
    nearbyAmenities: ["Sanctuary of Truth", "Wongamat Beach", "Naklua Fish Market", "Windmill Plaza"],
    article: "<p>Nestled next to the iconic Sanctuary of Truth, <strong>The Sanctuary Wongamat</strong> is a resort-style luxury low-rise residence. Featuring natural wood design, beach pools, and quiet gardens, it is a private coastal haven.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer convenient, high-quality laundry pickup and dry cleaning delivered right back to your door at The Sanctuary.</p>"
  },
  {
    slug: "lumpini-ville-naklua",
    name: "Lumpini Ville Naklua-Wongamat",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1500,
    averagePrice: "฿9,000 - ฿20,000 / month",
    transport: "On North Pattaya Road, 5 min to beach",
    address: "North Pattaya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Lumpini+Ville+Naklua-Wongamat",
    website: "https://www.lpn.co.th",
    nearbyAmenities: ["Terminal 21 Pattaya", "Makro North Pattaya", "Pattaya Bus Terminal", "Tesco Lotus"],
    article: "<p><strong>Lumpini Ville Naklua-Wongamat</strong> is a large residential community located at the intersection of North Pattaya Road and Naklua. With standard pools, playgrounds, and close access to transit routes, it is popular with local professionals.</p><p>We provide standard laundry and dry cleaning services. <strong>That Laundry Shop</strong> coordinates pickups from Lumpini Ville concierge for a hassle-free experience.</p>"
  },
  {
    slug: "lumpini-park-beach-jomtien",
    name: "Lumpini Park Beach Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1154,
    averagePrice: "฿11,000 - ฿25,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Lumpini+Park+Beach+Jomtien",
    website: "https://www.lpn.co.th",
    nearbyAmenities: ["Jomtien Beach", "Pupen Seafood", "Lung Sawai", "Floating Market"],
    article: "<p><strong>Lumpini Park Beach Jomtien</strong> is a premium high-rise community situated right on Jomtien Beach. Boasting dual swimming pools, sky gardens, and convenient access to seafood restaurants, it is a popular long-term choice.</p><p>Stay fresh with <strong>That Laundry Shop</strong>. We provide professional wash, fold, and dry cleaning services with daily pickups at Lumpini Park Beach.</p>"
  },
  {
    slug: "city-center-residence",
    name: "City Center Residence",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 668,
    averagePrice: "฿10,000 - ฿24,000 / month",
    transport: "Located in Central Pattaya, near Third Road",
    address: "Pattaya Third Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=City+Center+Residence+Pattaya",
    website: "https://www.matrixpattaya.com",
    nearbyAmenities: ["The Avenue Pattaya", "Tukcom IT Mall", "Central Festival", "Pattaya Third Road"],
    article: "<p><strong>City Center Residence</strong> is a modern low-rise complex featuring a large circular pool, fitness centers, and quiet residential yards, offering high-value modern living in central Pattaya.</p><p>We collect and deliver your laundry directly. <strong>That Laundry Shop</strong> is your professional partner for dry cleaning and laundry pickup at City Center Residence.</p>"
  },
  {
    slug: "apus-condo",
    name: "Apus Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 158,
    averagePrice: "฿16,000 - ฿35,000 / month",
    transport: "Located in Central Pattaya, off Klang Road",
    address: "Pattaya Klang Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Apus+Condominium+Pattaya",
    website: "http://www.apuscondo.com",
    nearbyAmenities: ["Big C Extra Klang", "Foodland Supermarket", "Harbor Pattaya Mall", "Central Festival"],
    article: "<p><strong>Apus Condominium</strong> is a premium low-rise resort-style residence located in Central Pattaya. Featuring resort-style pools, fitness suites, and tropical gardens, it is highly popular with executives.</p><p>Enjoy convenient laundry service from <strong>That Laundry Shop</strong>. We collect your bags from the Apus front reception and return everything clean and pressed.</p>"
  },
  {
    slug: "pattaya-tower",
    name: "Pattaya Tower Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 320,
    averagePrice: "฿12,000 - ฿28,000 / month",
    transport: "Located in Central Pattaya, near Beach Road",
    address: "Pattaya Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Pattaya+Tower+Condominium",
    website: "https://www.pattayatower.com",
    nearbyAmenities: ["Pattaya Beach", "Central Festival", "Mike Shopping Mall", "Hard Rock Hotel"],
    article: "<p><strong>Pattaya Tower</strong> is a classic high-rise offering spectacular ocean and harbor views of Pattaya Bay. Located in the absolute center of Pattaya, it is a short walk to all main shopping and beach points.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the front desk of Pattaya Tower.</p>"
  },
  {
    slug: "view-talay-1",
    name: "View Talay 1 Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1650,
    averagePrice: "฿8,000 - ฿18,000 / month",
    transport: "On Thappraya Road Jomtien, near Bus Station",
    address: "Thappraya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=View+Talay+1+Jomtien",
    website: "https://www.viewtalay.com",
    nearbyAmenities: ["Suvarnabhumi Airport Bus Station", "Food Mart", "Pan Pan Restaurant", "Dongtan Beach"],
    article: "<p><strong>View Talay 1 Jomtien</strong> is a massive double-tower development. Featuring giant swimming pools, supermarket zones inside the lobby, and close transit to Suvarnabhumi Airport bus terminal, it is a popular expat gateway.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from View Talay 1.</p>"
  },
  {
    slug: "view-talay-2",
    name: "View Talay 2 Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1900,
    averagePrice: "฿8,500 - ฿20,000 / month",
    transport: "On Thappraya Road Jomtien",
    address: "Thappraya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=View+Talay+2+Jomtien",
    website: "https://www.viewtalay.com",
    nearbyAmenities: ["Dongtan Beach", "Food Mart", "Pratumnak Hill", "Jomtien Second Road"],
    article: "<p>Featuring expansive layouts and a massive central pool deck, <strong>View Talay 2 Jomtien</strong> is a classic residential complex. Its proximity to both Dongtan beach and Thappraya restaurants makes it a favorite long-term home.</p><p>Trust your garments to <strong>That Laundry Shop</strong>. We offer convenient, high-quality laundry pickup and dry cleaning delivered right back to your door at View Talay 2.</p>"
  },
  {
    slug: "view-talay-5",
    name: "View Talay 5 Beachfront",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1100,
    averagePrice: "฿12,000 - ฿30,000 / month",
    transport: "Direct beach access to Dongtan Beach",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=View+Talay+5+Beachfront",
    website: "https://www.viewtalay.com",
    nearbyAmenities: ["Dongtan Beach", "Jomtien Beach Road", "Pan Pan Restaurant", "Pratumnak Hill"],
    article: "<p>Offering private gated beachfront access to Dongtan Beach, <strong>View Talay 5</strong> is a premium high-rise development. Featuring standard gyms, sea-view pools, and large balconies, it blends beach proximity with privacy.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at View Talay 5.</p>"
  },
  {
    slug: "view-talay-6",
    name: "View Talay 6 Central Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 1000,
    averagePrice: "฿18,000 - ฿45,000 / month",
    transport: "Adjacent to Central Festival Pattaya Beach",
    address: "Pattaya Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=View+Talay+6+Central+Pattaya",
    website: "https://www.viewtalay.com",
    nearbyAmenities: ["Central Festival Pattaya Beach", "Pattaya Beach Road", "Walking Street", "Mike Shopping Mall"],
    article: "<p><strong>View Talay 6</strong> is located in the absolute center of Pattaya next to Central Festival. It provides stunning bay views, a large outdoor pool, and private access to the beach and shopping mall.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of View Talay 6, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "view-talay-7",
    name: "View Talay 7 Beachfront",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 950,
    averagePrice: "฿15,000 - ฿38,000 / month",
    transport: "Direct beach access to Dongtan Beach",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=View+Talay+7+Beachfront",
    website: "https://www.viewtalay.com",
    nearbyAmenities: ["Dongtan Beach", "Jomtien Bus Station", "Rompho Complex", "Food Mart"],
    article: "<p>Featuring absolute private beachfront access to Dongtan Beach and sea vistas from all floors, <strong>View Talay 7</strong> is a highly popular high-rise. It offers direct keycard access to the pedestrian beach walk.</p><p>We provide professional dry cleaning and quick laundry services. <strong>That Laundry Shop</strong> collects your garments directly from View Talay 7 lobby desk.</p>"
  },
  {
    slug: "grand-condotel",
    name: "Grand Condotel Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 450,
    averagePrice: "฿20,000 - ฿55,000 / month",
    transport: "Direct beach access to Dongtan Beach",
    address: "Thappraya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Grand+Condotel+Jomtien",
    website: "http://www.grandcondotel.com",
    nearbyAmenities: ["Dongtan Beach", "Suvarnabhumi Bus Station", "Food Mart", "Pan Pan Restaurant"],
    article: "<p><strong>Grand Condotel Jomtien</strong> is a premium beachfront development featuring tennis courts, standard swimming pools, private beach access, and round-the-clock security, popular with long-term retirees.</p><p>Make laundry day a breeze. <strong>That Laundry Shop</strong> offers direct pickup and delivery for dry cleaning and everyday laundry at Grand Condotel.</p>"
  },
  {
    slug: "royal-cliff-garden",
    name: "Royal Cliff Garden Suites",
    city: "Pattaya",
    type: "condo",
    stars: 5,
    totalRooms: 204,
    averagePrice: "฿45,000 - ฿130,000 / month",
    transport: "On Pratumnak Cliff, near Royal Cliff Hotel",
    address: "Kasetsin Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Royal+Cliff+Garden+Suites",
    website: "http://www.royalcliffgarden.com",
    nearbyAmenities: ["Royal Cliff Hotels Group", "Cozy Beach", "Bali Hai Pier", "Fitz Club"],
    article: "<p><strong>Royal Cliff Garden Suites</strong> is an ultra-exclusive high-rise condominium located on the cliffs of Pratumnak. With private elevators, huge units (mostly over 200 sqm), sea panoramas, and lush gardens, it is a premier address.</p><p>We provide premium dry cleaning and daily laundry delivery at Royal Cliff Garden, coordinating pickups directly from the lobby desk.</p>"
  },
  {
    slug: "south-beach-condo",
    name: "South Beach Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 78,
    averagePrice: "฿12,000 - ฿26,000 / month",
    transport: "Located on Pratumnak Soi 6",
    address: "Pratumnak Soi 6, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=South+Beach+Condominium",
    website: "http://www.southbeachpattaya.com",
    nearbyAmenities: ["Pratumnak Beach", "Patisse Cafe", "Big Buddha", "Pattaya Park"],
    article: "<p><strong>South Beach Condominium</strong> is a boutique low-rise residence offering modern loft apartments, a rooftop pool, and convenient access to Pratumnak Beach. It is popular with quiet holidaymakers.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services at South Beach.</p>"
  },
  {
    slug: "executive-residence",
    name: "Executive Residence Pratumnak",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 120,
    averagePrice: "฿14,000 - ฿30,000 / month",
    transport: "Located in Kasetsin Pratumnak",
    address: "Kasetsin Soi 7, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Executive+Residence+Pratumnak",
    website: "https://www.executiveresidencepattaya.com",
    nearbyAmenities: ["Cozy Beach", "Chocolate Factory", "Sky Gallery", "Bali Hai Pier"],
    article: "<p>Nestled in the quiet Kasetsin street, <strong>Executive Residence Pratumnak</strong> offers large apartments, swimming pools, fitness centers, and close beach access, providing premium residential living.</p><p>Enjoy hotel-standard dry cleaning and pressing services at your home. <strong>That Laundry Shop</strong> coordinates pickups from the front desk of Executive Residence.</p>"
  },
  {
    slug: "patta-let",
    name: "Patta Let Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 180,
    averagePrice: "฿12,000 - ฿25,000 / month",
    transport: "Located in East Pattaya, near Sukhumvit Road",
    address: "East Pattaya, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Patta+Let+Pattaya",
    website: "http://www.pattaleto.com",
    nearbyAmenities: ["Tesco Lotus South Pattaya", "Outlet Mall", "Sukhumvit Road", "Jomtien Beach"],
    article: "<p><strong>Patta Let</strong> is a premium townhouse and residential development in East Pattaya. Offering quiet suburban layouts, parks, and pool facilities, it is a popular residential hub for families.</p><p>Keep your clothes pristine. <strong>That Laundry Shop</strong> provides premium dry cleaning and daily laundry delivery at Patta Let, collecting items straight from your door.</p>"
  },
  {
    slug: "chateau-dale",
    name: "Chateau Dale Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 240,
    averagePrice: "฿15,000 - ฿35,000 / month",
    transport: "On Thappraya Road, 10 min to beach",
    address: "Thappraya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Chateau+Dale+Condominium",
    website: "https://www.chateaudale.com",
    nearbyAmenities: ["Food Mart", "Pan Pan Restaurant", "Jomtien Beach", "Sugar Hut"],
    article: "<p><strong>Chateau Dale</strong> is a resort-style low-rise complex on Thappraya Road. Boasting beautiful mature tropical gardens, massive swimming pools, and quiet residential spaces, it is a highly popular retreat.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at Chateau Dale.</p>"
  },
  {
    slug: "j-condo-pattaya",
    name: "J Condo Sukhumvit Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 490,
    averagePrice: "฿10,000 - ฿22,000 / month",
    transport: "Located near Sukhumvit Central Pattaya",
    address: "Sukhumvit Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=J+Condo+Sukhumvit+Pattaya",
    website: "http://www.jcondopattaya.com",
    nearbyAmenities: ["King Power Pattaya", "Big C Extra Klang", "Harbor Mall", "Sukhumvit Road"],
    article: "<p><strong>J Condo</strong> is a modern high-rise located near Sukhumvit Road in Central Pattaya. With swimming pools, standard fitness centers, and close transit links to industrial hubs and central areas, it serves local executives.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of J Condo, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "acqa-condo",
    name: "Acqua Condominium Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 309,
    averagePrice: "฿12,000 - ฿30,000 / month",
    transport: "150m to Jomtien Beach",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Acqua+Condominium+Jomtien",
    website: "https://www.acquacondo.com",
    nearbyAmenities: ["Jomtien Beach", "Rompho Complex", "Jomtien Night Market", "Tesco Express"],
    article: "<p><strong>Acqua Condominium Jomtien</strong> is a premium low-rise resort featuring rooftop pools, fitness centers, library lounges, and a modern kid play area, offering luxury beach living.</p><p>We provide professional dry cleaning and quick laundry services. <strong>That Laundry Shop</strong> collects your garments directly from Acqua lobby desk.</p>"
  },
  {
    slug: "lumpini-park-beach-jomtien-2",
    name: "Lumpini Park Beach Jomtien Tower B",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 800,
    averagePrice: "฿10,000 - ฿22,000 / month",
    transport: "Fronting Jomtien Beach Road",
    address: "Jomtien Beach Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Lumpini+Park+Beach+Jomtien",
    website: "https://www.lpn.co.th",
    nearbyAmenities: ["Jomtien Beach", "Lung Sawai Seafood", "Pattaya Floating Market", "Chaiyapruek Road"],
    article: "<p>Located directly on the beachfront of Jomtien, <strong>Lumpini Park Beach Jomtien Tower B</strong> is a popular residential choice. It features sea-view gym rooms, standard pools, and easy transit access.</p><p>Make laundry day a breeze. <strong>That Laundry Shop</strong> offers direct pickup and delivery for dry cleaning and everyday laundry at Lumpini Park Beach Tower B.</p>"
  },
  {
    slug: "sig-condo",
    name: "Signature Condominium Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 120,
    averagePrice: "฿15,000 - ฿35,000 / month",
    transport: "Located in South Pattaya, off Third Road",
    address: "South Pattaya, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Signature+Condominium+Pattaya",
    website: "http://www.signaturecondo.com",
    nearbyAmenities: ["Walking Street", "Bali Hai Pier", "Tukcom IT Mall", "Pattaya South"],
    article: "<p><strong>Signature Condominium</strong> is a resort-style low-rise located in South Pattaya. Offering rooftop pools, sky gyms, and close proximity to South Pattaya's shopping hubs, it fits active lifestyles.</p><p>We provide premium dry cleaning and daily laundry delivery at Signature, coordinating pickups directly from the lobby desk.</p>"
  },
  {
    slug: "lumpini-ville-naklua-2",
    name: "Lumpini Ville Naklua Tower C",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 600,
    averagePrice: "฿8,500 - ฿18,000 / month",
    transport: "On North Pattaya Road",
    address: "North Pattaya Road, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Lumpini+Ville+Naklua",
    website: "https://www.lpn.co.th",
    nearbyAmenities: ["Pattaya Bus Terminal", "Terminal 21 Pattaya", "Makro North Pattaya", "Sukhumvit Road"],
    article: "<p><strong>Lumpini Ville Naklua Tower C</strong> offers convenient living near main highways and central shopping hubs. It has excellent public spaces, pools, and recreational zones.</p><p>Trust your laundry with professionals. <strong>That Laundry Shop</strong> provides convenient pickup and delivery for laundry and dry cleaning services at Lumpini Ville Tower C.</p>"
  },
  {
    slug: "wongamat-residence",
    name: "Wongamat Residence Condominium",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 150,
    averagePrice: "฿15,000 - ฿35,000 / month",
    transport: "Located in Naklua, Soi 16",
    address: "Naklua Soi 16, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Wongamat+Residence+Condominium",
    website: "https://www.wongamatresidence.com",
    nearbyAmenities: ["Wongamat Beach", "Sanctuary of Truth", "Windmill Plaza", "Rim Talay Seafood"],
    article: "<p>Offering a cozy residential lifestyle near Wongamat Beach, <strong>Wongamat Residence</strong> features rooftop swimming pools, standard fitness facilities, and landscaped gardens.</p><p>We provide professional laundry services. <strong>That Laundry Shop</strong> picks up your dry cleaning and everyday laundry from the front desk of Wongamat Residence.</p>"
  },
  {
    slug: "royal-park-residence",
    name: "Royal Park Residence Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 180,
    averagePrice: "฿10,000 - ฿22,000 / month",
    transport: "Located in Jomtien, near Beach Road",
    address: "Jomtien, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1479839672679-a46483c0e7c8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Royal+Park+Residence+Jomtien",
    website: "https://www.royalparkresidence.com",
    nearbyAmenities: ["Jomtien Beach", "Rompho Complex", "Tesco Express", "Sports Arena"],
    article: "<p><strong>Royal Park Residence</strong> features resort-style low-rise apartments, rooftop pools, and convenient beach access. It is popular with travelers seeking quiet coastal holidays.</p><p>Save time on laundry. <strong>That Laundry Shop</strong> offers reliable drop-off and pickup services at the lobby of Royal Park, keeping your clothes clean and fresh.</p>"
  },
  {
    slug: "tropicana-condo",
    name: "Tropicana Condominium Jomtien",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 220,
    averagePrice: "฿12,000 - ฿26,000 / month",
    transport: "Located in Jomtien, Soi 7",
    address: "Jomtien Soi 7, Pattaya City, Bang Lamung District, Chon Buri 20150",
    image: "https://images.unsplash.com/photo-1464938050520-ef2270bb8ce8?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=Tropicana+Condominium+Jomtien",
    website: "https://www.tropicanajomtien.com",
    nearbyAmenities: ["Jomtien Beach Soi 7", "Night Market", "Sports Bar", "Rompho Complex"],
    article: "<p>Nestled in Jomtien Soi 7, <strong>Tropicana Condominium</strong> offers tropical garden facilities, swimming pools, and co-working areas, a short walk from Jomtien Beach.</p><p>Get laundry sorted without hassle. <strong>That Laundry Shop</strong> provides next-day return on laundry and dry cleaning, collecting items straight from the lobby at Tropicana Jomtien.</p>"
  },
  {
    slug: "cc-condo-pattaya",
    name: "CC Condominium East Pattaya",
    city: "Pattaya",
    type: "condo",
    stars: 4,
    totalRooms: 380,
    averagePrice: "฿7,500 - ฿16,000 / month",
    transport: "Located in East Pattaya, near Siam Country Club",
    address: "East Pattaya, Pattaya City, Sattahip District, Chon Buri 20250",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80",
    mapLink: "https://maps.google.com/?q=CC+Condominium+Pattaya",
    website: "https://www.cccondo.com",
    nearbyAmenities: ["Siam Country Club", "Tesco Lotus East Pattaya", "Sukhumvit Road", "Pattaya Klang"],
    article: "<p><strong>CC Condominium</strong> is a modern residential development in East Pattaya. Offering quiet suburban living, standard pools, and easy commute routes, it serves local families.</p><p>We provide prompt laundry, dry cleaning, and bed linen services. <strong>That Laundry Shop</strong> coordinates pickups with the front desk at CC Condominium.</p>"
  }
];

async function seed() {
  console.log(`Seeding Pattaya Condos started. Total: ${pattayaCondos.length}`);
  
  let successCount = 0;
  let failCount = 0;
  
  for (const condo of pattayaCondos) {
    try {
      await prisma.location.upsert({
        where: { slug: condo.slug },
        update: {
          name: condo.name,
          city: condo.city,
          type: condo.type,
          stars: condo.stars,
          totalRooms: condo.totalRooms,
          averagePrice: condo.averagePrice,
          transport: condo.transport,
          address: condo.address,
          image: condo.image,
          mapLink: condo.mapLink,
          website: condo.website,
          nearbyAmenities: condo.nearbyAmenities,
          article: condo.article
        },
        create: condo
      });
      console.log(`Successfully seeded/updated: ${condo.name}`);
      successCount++;
    } catch (err) {
      console.error(`Failed to seed: ${condo.name}`, err);
      failCount++;
    }
  }
  
  console.log(`Seeding completed. Success: ${successCount}, Failed: ${failCount}`);
  
  try {
    const { revalidatePath } = require('next/cache');
    revalidatePath("/[locale]/hotels", "page");
    revalidatePath("/[locale]/condominiums", "page");
    revalidatePath("/[locale]/hotels/[slug]", "page");
    revalidatePath("/[locale]/condominiums/[slug]", "page");
    console.log("Revalidated frontend cache paths successfully.");
  } catch (revalErr) {
    console.log("Note: Skipped Next.js runtime revalidation (normal when running outside Next.js process).");
  }
}

seed()
  .catch(console.error)
  .finally(async () => {
    await prisma.$disconnect();
    pool.end();
  });
