export const countryCodes = [
  { name: "Afghanistan", code: "+93", label: "AF +93" },
  { name: "Albania", code: "+355", label: "AL +355" },
  { name: "Algeria", code: "+213", label: "DZ +213" },
  { name: "Andorra", code: "+376", label: "AD +376" },
  { name: "Angola", code: "+244", label: "AO +244" },
  { name: "Antigua and Barbuda", code: "+1", label: "AG +1" },
  { name: "Argentina", code: "+54", label: "AR +54" },
  { name: "Armenia", code: "+374", label: "AM +374" },
  { name: "Australia", code: "+61", label: "AU +61" },
  { name: "Austria", code: "+43", label: "AT +43" },
  { name: "Azerbaijan", code: "+994", label: "AZ +994" },
  { name: "Bahamas", code: "+1", label: "BS +1" },
  { name: "Bahrain", code: "+973", label: "BH +973" },
  { name: "Bangladesh", code: "+880", label: "BD +880" },
  { name: "Barbados", code: "+1", label: "BB +1" },
  { name: "Belarus", code: "+375", label: "BY +375" },
  { name: "Belgium", code: "+32", label: "BE +32" },
  { name: "Belize", code: "+501", label: "BZ +501" },
  { name: "Benin", code: "+229", label: "BJ +229" },
  { name: "Bhutan", code: "+975", label: "BT +975" },
  { name: "Bolivia", code: "+591", label: "BO +591" },
  { name: "Bosnia and Herzegovina", code: "+387", label: "BA +387" },
  { name: "Botswana", code: "+267", label: "BW +267" },
  { name: "Brazil", code: "+55", label: "BR +55" },
  { name: "Brunei", code: "+673", label: "BN +673" },
  { name: "Bulgaria", code: "+359", label: "BG +359" },
  { name: "Burkina Faso", code: "+226", label: "BF +226" },
  { name: "Burundi", code: "+257", label: "BI +257" },
  { name: "Cambodia", code: "+855", label: "KH +855" },
  { name: "Cameroon", code: "+237", label: "CM +237" },
  { name: "Canada", code: "+1", label: "CA +1" },
  { name: "Cape Verde", code: "+238", label: "CV +238" },
  { name: "Central African Republic", code: "+236", label: "CF +236" },
  { name: "Chad", code: "+235", label: "TD +235" },
  { name: "Chile", code: "+56", label: "CL +56" },
  { name: "China", code: "+86", label: "CN +86" },
  { name: "Colombia", code: "+57", label: "CO +57" },
  { name: "Comoros", code: "+269", label: "KM +269" },
  { name: "Congo", code: "+242", label: "CG +242" },
  { name: "Costa Rica", code: "+506", label: "CR +506" },
  { name: "Croatia", code: "+385", label: "HR +385" },
  { name: "Cuba", code: "+53", label: "CU +53" },
  { name: "Cyprus", code: "+357", label: "CY +357" },
  { name: "Czech Republic", code: "+420", label: "CZ +420" },
  { name: "Denmark", code: "+45", label: "DK +45" },
  { name: "Djibouti", code: "+253", label: "DJ +253" },
  { name: "Dominica", code: "+1", label: "DM +1" },
  { name: "Dominican Republic", code: "+1", label: "DO +1" },
  { name: "Ecuador", code: "+593", label: "EC +593" },
  { name: "Egypt", code: "+20", label: "EG +20" },
  { name: "El Salvador", code: "+503", label: "SV +503" },
  { name: "Equatorial Guinea", code: "+240", label: "GQ +240" },
  { name: "Eritrea", code: "+291", label: "ER +291" },
  { name: "Estonia", code: "+372", label: "EE +372" },
  { name: "Ethiopia", code: "+251", label: "ET +251" },
  { name: "Fiji", code: "+679", label: "FJ +679" },
  { name: "Finland", code: "+358", label: "FI +358" },
  { name: "France", code: "+33", label: "FR +33" },
  { name: "Gabon", code: "+241", label: "GA +241" },
  { name: "Gambia", code: "+220", label: "GM +220" },
  { name: "Georgia", code: "+995", label: "GE +995" },
  { name: "Germany", code: "+49", label: "DE +49" },
  { name: "Ghana", code: "+233", label: "GH +233" },
  { name: "Greece", code: "+30", label: "GR +30" },
  { name: "Grenada", code: "+1", label: "GD +1" },
  { name: "Guatemala", code: "+502", label: "GT +502" },
  { name: "Guinea", code: "+224", label: "GN +224" },
  { name: "Guinea-Bissau", code: "+245", label: "GW +245" },
  { name: "Guyana", code: "+592", label: "GY +592" },
  { name: "Haiti", code: "+509", label: "HT +509" },
  { name: "Honduras", code: "+504", label: "HN +504" },
  { name: "Hungary", code: "+36", label: "HU +36" },
  { name: "Iceland", code: "+354", label: "IS +354" },
  { name: "India", code: "+91", label: "IN +91" },
  { name: "Indonesia", code: "+62", label: "ID +62" },
  { name: "Iran", code: "+98", label: "IR +98" },
  { name: "Iraq", code: "+964", label: "IQ +964" },
  { name: "Ireland", code: "+353", label: "IE +353" },
  { name: "Israel", code: "+972", label: "IL +972" },
  { name: "Italy", code: "+39", label: "IT +39" },
  { name: "Jamaica", code: "+1", label: "JM +1" },
  { name: "Japan", code: "+81", label: "JP +81" },
  { name: "Jordan", code: "+962", label: "JO +962" },
  { name: "Kazakhstan", code: "+7", label: "KZ +7" },
  { name: "Kenya", code: "+254", label: "KE +254" },
  { name: "Kiribati", code: "+686", label: "KI +686" },
  { name: "North Korea", code: "+850", label: "KP +850" },
  { name: "South Korea", code: "+82", label: "KR +82" },
  { name: "Kuwait", code: "+965", label: "KW +965" },
  { name: "Kyrgyzstan", code: "+996", label: "KG +996" },
  { name: "Laos", code: "+856", label: "LA +856" },
  { name: "Latvia", code: "+371", label: "LV +371" },
  { name: "Lebanon", code: "+961", label: "LB +961" },
  { name: "Lesotho", code: "+266", label: "LS +266" },
  { name: "Liberia", code: "+231", label: "LR +231" },
  { name: "Libya", code: "+218", label: "LY +218" },
  { name: "Liechtenstein", code: "+423", label: "LI +423" },
  { name: "Lithuania", code: "+370", label: "LT +370" },
  { name: "Luxembourg", code: "+352", label: "LU +352" },
  { name: "Macau", code: "+853", label: "MO +853" },
  { name: "Macedonia", code: "+389", label: "MK +389" },
  { name: "Madagascar", code: "+261", label: "MG +261" },
  { name: "Malawi", code: "+265", label: "MW +265" },
  { name: "Malaysia", code: "+60", label: "MY +60" },
  { name: "Maldives", code: "+960", label: "MV +960" },
  { name: "Mali", code: "+223", label: "ML +223" },
  { name: "Malta", code: "+356", label: "MT +356" },
  { name: "Marshall Islands", code: "+692", label: "MH +692" },
  { name: "Mauritania", code: "+222", label: "MR +222" },
  { name: "Mauritius", code: "+230", label: "MU +230" },
  { name: "Mexico", code: "+52", label: "MX +52" },
  { name: "Micronesia", code: "+691", label: "FM +691" },
  { name: "Moldova", code: "+373", label: "MD +373" },
  { name: "Monaco", code: "+377", label: "MC +377" },
  { name: "Mongolia", code: "+976", label: "MN +976" },
  { name: "Montenegro", code: "+382", label: "ME +382" },
  { name: "Morocco", code: "+212", label: "MA +212" },
  { name: "Mozambique", code: "+258", label: "MZ +258" },
  { name: "Myanmar", code: "+95", label: "MM +95" },
  { name: "Namibia", code: "+264", label: "NA +264" },
  { name: "Nauru", code: "+674", label: "NR +674" },
  { name: "Nepal", code: "+977", label: "NP +977" },
  { name: "Netherlands", code: "+31", label: "NL +31" },
  { name: "New Zealand", code: "+64", label: "NZ +64" },
  { name: "Nicaragua", code: "+505", label: "NI +505" },
  { name: "Niger", code: "+227", label: "NE +227" },
  { name: "Nigeria", code: "+234", label: "NG +234" },
  { name: "Norway", code: "+47", label: "NO +47" },
  { name: "Oman", code: "+968", label: "OM +968" },
  { name: "Pakistan", code: "+92", label: "PK +92" },
  { name: "Palau", code: "+680", label: "PW +680" },
  { name: "Panama", code: "+507", label: "PA +507" },
  { name: "Papua New Guinea", code: "+675", label: "PG +675" },
  { name: "Paraguay", code: "+595", label: "PY +595" },
  { name: "Peru", code: "+51", label: "PE +51" },
  { name: "Philippines", code: "+63", label: "PH +63" },
  { name: "Poland", code: "+48", label: "PL +48" },
  { name: "Portugal", code: "+351", label: "PT +351" },
  { name: "Qatar", code: "+974", label: "QA +974" },
  { name: "Romania", code: "+40", label: "RO +40" },
  { name: "Russia", code: "+7", label: "RU +7" },
  { name: "Rwanda", code: "+250", label: "RW +250" },
  { name: "Saint Kitts and Nevis", code: "+1", label: "KN +1" },
  { name: "Saint Lucia", code: "+1", label: "LC +1" },
  { name: "Saint Vincent and the Grenadines", code: "+1", label: "VC +1" },
  { name: "Samoa", code: "+685", label: "WS +685" },
  { name: "San Marino", code: "+378", label: "SM +378" },
  { name: "Sao Tome and Principe", code: "+239", label: "ST +239" },
  { name: "Saudi Arabia", code: "+966", label: "SA +966" },
  { name: "Senegal", code: "+221", label: "SN +221" },
  { name: "Serbia", code: "+381", label: "RS +381" },
  { name: "Seychelles", code: "+248", label: "SC +248" },
  { name: "Sierra Leone", code: "+232", label: "SL +232" },
  { name: "Singapore", code: "+65", label: "SG +65" },
  { name: "Slovakia", code: "+421", label: "SK +421" },
  { name: "Slovenia", code: "+386", label: "SI +386" },
  { name: "Solomon Islands", code: "+677", label: "SB +677" },
  { name: "Somalia", code: "+252", label: "SO +252" },
  { name: "South Africa", code: "+27", label: "ZA +27" },
  { name: "Spain", code: "+34", label: "ES +34" },
  { name: "Sri Lanka", code: "+94", label: "LK +94" },
  { name: "Sudan", code: "+249", label: "SD +249" },
  { name: "Suriname", code: "+597", label: "SR +597" },
  { name: "Swaziland", code: "+268", label: "SZ +268" },
  { name: "Sweden", code: "+46", label: "SE +46" },
  { name: "Switzerland", code: "+41", label: "CH +41" },
  { name: "Syria", code: "+963", label: "SY +963" },
  { name: "Taiwan", code: "+886", label: "TW +886" },
  { name: "Tajikistan", code: "+992", label: "TJ +992" },
  { name: "Tanzania", code: "+255", label: "TZ +255" },
  { name: "Thailand", code: "+66", label: "TH +66" },
  { name: "Timor-Leste", code: "+670", label: "TL +670" },
  { name: "Togo", code: "+228", label: "TG +228" },
  { name: "Tonga", code: "+676", label: "TO +676" },
  { name: "Trinidad and Tobago", code: "+1", label: "TT +1" },
  { name: "Tunisia", code: "+216", label: "TN +216" },
  { name: "Turkey", code: "+90", label: "TR +90" },
  { name: "Turkmenistan", code: "+993", label: "TM +993" },
  { name: "Tuvalu", code: "+688", label: "TV +688" },
  { name: "Uganda", code: "+256", label: "UG +256" },
  { name: "Ukraine", code: "+380", label: "UA +380" },
  { name: "United Arab Emirates", code: "+971", label: "AE +971" },
  { name: "United Kingdom", code: "+44", label: "GB +44" },
  { name: "United States", code: "+1", label: "US +1" },
  { name: "Uruguay", code: "+598", label: "UY +598" },
  { name: "Uzbekistan", code: "+998", label: "UZ +998" },
  { name: "Vanuatu", code: "+678", label: "VU +678" },
  { name: "Vatican City", code: "+39", label: "VA +39" },
  { name: "Venezuela", code: "+58", label: "VE +58" },
  { name: "Vietnam", code: "+84", label: "VN +84" },
  { name: "Yemen", code: "+967", label: "YE +967" },
  { name: "Zambia", code: "+260", label: "ZM +260" },
  { name: "Zimbabwe", code: "+263", label: "ZW +263" }
];
